"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";

type Language = "en" | "zh";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

const ZH: Record<string, string> = {
  "Your launch draft": "你的发行草稿",
  "Save draft": "保存草稿",
  "Restore draft": "恢复草稿",
  "Delete saved draft": "删除已保存的草稿",
  "Saved only in this browser, not to your wallet or the cloud. Restore replaces the current form. No funds move.": "仅保存在此浏览器中，不会写入钱包或云端。恢复将替换当前表单，不会转移资金。",
  "Draft saved on this browser. No transaction submitted. Unuploaded image files are not included.": "草稿已保存在此浏览器中。未提交交易，未上传的图片文件不会保存。",
  "Draft restored. Review every field again before launching.": "草稿已恢复。发行前请重新检查每个字段。",
  "Draft restored. Choose a currently approved pair before launching.": "草稿已恢复。发行前请选择当前已批准的配对资产。",
  "Saved draft deleted. Current form is unchanged.": "已删除保存的草稿。当前表单保持不变。",
  "Browser storage is unavailable. Drafts cannot be saved on this device.": "浏览器存储不可用，无法在此设备保存草稿。",
  "Choose an image file": "选择图片文件",
  "Drop a square PNG, JPEG or WebP · up to 2 MiB": "拖入方形 PNG、JPEG 或 WebP 图片 · 最大 2 MiB",
  "Token image file": "代币图片文件",
  "Upload image": "上传图片",
  "Uploading…": "正在上传…",
  "Remove file": "移除文件",
  "File preview is available. Upload hosting is not connected yet; use a public image URL or IPFS URI to launch.": "可预览本地文件。上传托管尚未连接；发行时请使用公开图片 URL 或 IPFS URI。",
  "Uploading publishes your image to IPFS. A wallet message authorizes storage only; it cannot spend funds. Keep your own pinned copy.": "上传会将图片公开发布到 IPFS。钱包消息仅授权存储，不能花费资金。请保留自己固定存储的副本。",
  "Fortune records the URI at launch. HTTP-hosted content can change; an IPFS CID fixes the content but still needs hosting.": "Fortune 在发行时记录 URI。HTTP 托管内容可能更改；IPFS CID 固定内容，但仍需要托管。",
  "Image uploaded to IPFS. Save a copy of the URI; availability depends on continued pinning.": "图片已上传到 IPFS。请保存 URI；可用性取决于持续固定存储。",
  "Project links": "项目链接",
  "More project links": "更多项目链接",
  "What is your token about?": "介绍一下你的代币？",
  "Optional. Stored as fixed onchain metadata with your token.": "可选。将作为固定链上元数据与代币一同保存。",
  "Advanced · custom metadata URI": "高级 · 自定义元数据 URI",
  "Metadata URI": "元数据 URI",
  "Load metadata": "加载元数据",
  "Apply imported fields": "应用导入的字段",
  "Import JSON into the fields above. Standard stores those fields onchain, not the JSON URI. Unknown JSON fields are ignored; imported fields replace the current identity only when you apply them.": "将 JSON 导入上方字段。Standard 在链上存储这些字段，而不是 JSON URI。未知字段会被忽略；只有点击应用时才会替换当前资料。",
  "The JSON must include name, symbol and image. Public HTTPS hosts must allow CORS. No server proxy or wallet signature is used.": "JSON 必须包含 name、symbol 和 image。公开 HTTPS 主机必须允许 CORS。不使用服务器代理或钱包签名。",
  "Metadata fields imported. Check the description, image and every link before reviewing.": "元数据字段已导入。请检查简介、图片及每个链接。",
  "Dev Launch": "开发者发行",
  "Custom creator-fee model · not implemented or approved": "自定义创建者费率模型 · 尚未实现或批准",
  "One pair · one graduation pool": "单一配对 · 单一毕业池",
  "Two-to-five-pool launches require a separate reviewed release. This form does not enable multi-pair research or change the frozen Standard candidate.": "两到五池发行需要单独审核的版本。此表单不会启用多配对研究功能或更改冻结的 Standard 候选。",
  "All BNB": "全部 BNB",
  "Any token": "任意代币",
  "Pair categories": "配对分类",
  "Discovery only · not selectable": "仅供发现 · 无法选择",
  "Catalog entries are not registry approval. Mainnet Standard is WBNB-only; testnet uses its own valueless assets. Tokenized stocks require a verified compatible BSC deployment and separate eligibility review.": "目录收录并非注册表批准。主网 Standard 仅支持 WBNB；测试网使用无价值测试资产。代币化股票需要已验证的兼容 BSC 部署及单独资格审查。",
  "Explore pair research →": "探索配对研究 →",
  "Advanced · curve economics": "高级 · 曲线经济参数",
  "Paste an address to check the active network. Readable BEP-20 metadata alone does not make a token safe or approved.": "粘贴地址以检查当前网络。仅能读取 BEP-20 元数据不代表代币安全或已获批准。",
  "Token contract address": "代币合约地址",
  "Check token": "检查代币",
  "Use checked pair": "使用已检查的配对",
  "Checking…": "正在检查…",
  "Registry checks passed. Release readiness and transaction preflight still apply.": "注册表检查已通过。仍需满足发布条件及交易预检查。",
  "Not available for this launch.": "本次发行不可用。",
  "About this project": "关于此项目",
  "Project metadata could not be verified from the onchain registry.": "无法从链上注册表验证项目元数据。",
  "Loading onchain project metadata…": "正在加载链上项目元数据…",
  "Creator-provided content and external links are not endorsed by Fortune.": "Fortune 不为创建者提供的内容或外部链接背书。",
  "Metadata fields are frozen onchain. External website and image hosting may still change.": "元数据字段已在链上冻结。外部网站和图片托管仍可能更改。",
  "Creator-editable metadata. Check the current onchain revision.": "创建者可编辑的元数据。请检查当前链上版本。",
  "View metadata and block evidence ↗": "查看元数据及区块证据 ↗",
  "Overview": "概览",
  "Public Testnet": "公开测试网",
  "API": "开发接口",
  "Public Alpha": "公开 Alpha",
  "Switch testnet": "切换测试网",
  "Report a bug ↗": "报告问题 ↗",
  "Connect wallet": "连接钱包",
  "Connecting…": "连接中…",
  "BSC Testnet wallet connected": "BSC 测试网钱包已连接",
  "Wallet connected · switch to BSC Testnet": "钱包已连接 · 请切换到 BSC 测试网",
  "Fortune · public BSC Testnet alpha": "Fortune · BSC 公开测试版",
  "Test assets only · no real funds": "仅限测试资产 · 请勿使用真实资金",

  "FORTUNE PUBLIC BSC TESTNET ALPHA": "FORTUNE BSC 公开测试版",
  "Launch against anything. Test it for real.": "万物皆可发行。现在真实测试。",
  "Fortune is now running an onchain public alpha on BNB Smart Chain Testnet. Create a real Fortune test token, trade its curve with valueless mock fUSD, and graduate it into a real Pancake V3 testnet pool.": "Fortune 现已在 BNB Smart Chain 测试网上开放公开测试。你可以创建真实的 Fortune 测试代币，用无价值的模拟 fUSD 在曲线上交易，并将代币毕业到真实的 Pancake V3 测试网池。",
  "Open public testnet →": "进入公开测试网 →",
  "Developer API": "开发者 API",
  "Public alpha only. The contracts are pre-audit and mainnet remains disabled. Do not use real funds.": "仅限公开测试版。合约尚未完成独立审计，主网仍未开放。请勿使用真实资金。",
  "RELEASE GATE · PASSED": "发布测试 · 已通过",
  "39/39 tests": "39/39 项测试",
  "1,000 fuzz runs": "1,000 次模糊测试",
  "7,500/7,500 requests": "7,500/7,500 次请求",
  "3 real graduations": "3 次真实毕业",
  "Peak measured throughput": "实测峰值吞吐量",
  "500-concurrent p95": "500 并发 p95",
  "Release p95 limit": "发布 p95 上限",
  "Post-storm invariants": "压力测试后不变量",
  "16/16 passed": "16/16 通过",
  "WHAT IS LIVE": "当前已上线",
  "One narrow, real alpha path.": "一条精简但真实的测试路径。",
  "Create": "创建",
  "Create an actual Fortune token through the deployed BSC Testnet factory. Every Fortune token is CREATE2-deployed with the required 0xfe suffix.": "通过已部署的 BSC 测试网工厂创建真实的 Fortune 测试代币。每个 Fortune 代币都通过 CREATE2 部署，并带有规定的 0xfe 地址后缀。",
  "Wallet-signed": "钱包签名",
  "Trade": "交易",
  "Mint valueless mock fUSD, approve the new curve, and make an onchain test purchase against Fortune's canonical curve.": "铸造无价值的模拟 fUSD，授权新曲线，然后在 Fortune 的标准曲线上进行链上测试买入。",
  "Real testnet txs": "真实测试网交易",
  "Graduate": "毕业",
  "Permissionlessly finalize the launch into Pancake V3 testnet and permanently custody the resulting LP-position NFT in the Fortune locker.": "无需许可即可将发行毕业到 Pancake V3 测试网，并把生成的 LP 仓位 NFT 永久锁入 Fortune 锁仓合约。",
  "Pancake V3": "Pancake V3",
  "PUBLIC ALPHA DEPLOYMENT": "公开测试版部署",
  "Verify the contracts yourself.": "你可以自行验证所有合约。",
  "Factory on BscScan ↗": "在 BscScan 查看工厂 ↗",
  "Fortune Factory": "Fortune 工厂",
  "Asset Registry": "资产注册表",
  "Graduation adapter": "毕业适配器",
  "Permanent LP locker": "永久 LP 锁仓",
  "Mock fUSD": "模拟 fUSD",
  "Reference Pancake pool": "参考 Pancake 池",
  "ALPHA SCOPE": "测试版范围",
  "No fake markets or fake volume.": "不展示虚假市场或虚假交易量。",
  "Real testnet contracts": "真实测试网合约",
  "Real wallet signatures": "真实钱包签名",
  "Real Pancake V3 testnet": "真实 Pancake V3 测试网",
  "Valueless test assets": "无价值测试资产",
  "Indexer/social features coming later": "索引器和社交功能稍后上线",

  "Try Fortune onchain.": "在链上体验 Fortune。",
  "Create a real Fortune testnet launch, trade its Basket Curve with free mock fUSD, and graduate it into a real Pancake V3 testnet pool. Test assets have no financial value.": "创建真实的 Fortune 测试网发行，用免费的模拟 fUSD 在篮子曲线上交易，并毕业到真实的 Pancake V3 测试网池。测试资产没有金融价值。",
  "Get tBNB gas ↗": "获取 tBNB Gas ↗",
  "TESTNET ONLY": "仅限测试网",
  "Chain 97 · never use real BNB or a wallet holding valuable assets. The fUSD faucet below mints a Fortune-owned mock token solely for testing.": "链 ID 97 · 不要使用真实 BNB，也不要使用持有有价值资产的钱包。下面的 fUSD 水龙头只会铸造 Fortune 的测试代币。",
  "Wallet + test funds": "钱包 + 测试资金",
  "tBNB pays gas. fUSD is the free quote asset used by this alpha deployment.": "tBNB 用于支付 Gas。fUSD 是此测试版使用的免费计价资产。",
  "Network": "网络",
  "BSC Testnet · 97": "BSC 测试网 · 97",
  "Wallet": "钱包",
  "Not connected": "未连接",
  "fUSD balance": "fUSD 余额",
  "Connect / switch testnet": "连接 / 切换测试网",
  "Faucet 250 fUSD": "领取 250 fUSD",
  "Minting…": "铸造中…",
  "Create a launch": "创建发行",
  "The public alpha uses the proven single-asset fUSD path and the live Fortune factory.": "公开测试版使用已验证的单资产 fUSD 路径和真实 Fortune 工厂。",
  "Token name": "代币名称",
  "Ticker": "代码",
  "Description": "简介",
  "Create testnet launch →": "创建测试网发行 →",
  "Creating launch…": "创建中…",
  "03 · CURVE → PANCAKE": "03 · 曲线 → PANCAKE",
  "Complete the testnet lifecycle": "完成完整测试网流程",
  "Launch transaction ↗": "发行交易 ↗",
  "Token": "代币",
  "Curve": "曲线",
  "Graduation target": "毕业目标",
  "$1 mock USD": "1 美元模拟价值",
  "Pancake fee tier": "Pancake 费率档",
  "Approve + buy 250 fUSD": "授权并买入 250 fUSD",
  "Buying…": "买入中…",
  "Finalize Pancake graduation": "完成 Pancake 毕业",
  "Graduating…": "毕业中…",
  "Create a launch to unlock the lifecycle test.": "先创建发行，才能进行完整流程测试。",
  "You will receive the real testnet token and curve addresses after the LaunchCreated event confirms.": "LaunchCreated 事件确认后，你会获得真实的测试网代币地址和曲线地址。",
  "TRANSACTION STATUS": "交易状态",
  "PUBLIC ALPHA CONTRACTS": "公开测试版合约",
  "Verify everything yourself": "自行验证全部内容",
  "Pancake graduation adapter": "Pancake 毕业适配器",

  "Connect a testnet wallet to begin.": "连接测试网钱包以开始。",
  "Wallet connected to BSC Testnet. Get tBNB for gas, then use the free fUSD test faucet below.": "钱包已连接到 BSC 测试网。先获取 tBNB 支付 Gas，再使用下方免费的 fUSD 测试水龙头。",
  "Wallet connection failed.": "钱包连接失败。",
  "250 fUSD test tokens minted to your wallet.": "已向你的钱包铸造 250 fUSD 测试代币。",
  "fUSD faucet transaction failed.": "fUSD 水龙头交易失败。",
  "Token name must be 1–64 characters.": "代币名称必须为 1–64 个字符。",
  "Ticker must be 1–16 characters.": "代币代码必须为 1–16 个字符。",
  "Finding your deterministic 0xfe token address…": "正在寻找确定性的 0xfe 代币地址…",
  "Confirm the Fortune launch transaction in your wallet.": "请在钱包中确认 Fortune 发行交易。",
  "Launch transaction confirmed, but the LaunchCreated event could not be decoded. Check the transaction in BscScan.": "发行交易已确认，但无法解析 LaunchCreated 事件。请在 BscScan 中查看交易。",
  "Launch created. Faucet fUSD if needed, then buy on the curve to drive it to graduation.": "发行已创建。如有需要先领取 fUSD，然后在曲线上买入以推动毕业。",
  "Approve 250 fUSD for this curve in your wallet.": "请在钱包中为此曲线授权 250 fUSD。",
  "Approval confirmed. Confirm the curve buy.": "授权已确认。请确认曲线买入交易。",
  "Curve reached GraduationReady. You can now finalize its Pancake V3 graduation.": "曲线已达到 GraduationReady。现在可以完成 Pancake V3 毕业。",
  "Buy confirmed. This curve has not reached GraduationReady yet.": "买入已确认。此曲线尚未达到 GraduationReady。",
  "Curve buy failed.": "曲线买入失败。",
  "Graduation preflight is not ready yet. The launch remains retryable.": "毕业预检查尚未通过。发行仍可稍后重试。",
  "Confirm the permissionless graduation transaction.": "请确认无需许可的毕业交易。",
  "Transaction confirmed but the curve did not reach PoolCreated. It can be retried.": "交易已确认，但曲线未达到 PoolCreated。可以重试。",
  "Graduation complete: Pancake V3 pool created and the LP-position NFT is permanently locked.": "毕业完成：Pancake V3 池已创建，LP 仓位 NFT 已永久锁定。",
  "Graduation failed.": "毕业失败。",
  "No injected EVM wallet found. Install MetaMask or another BSC-compatible wallet.": "未检测到 EVM 钱包。请安装 MetaMask 或其他兼容 BSC 的钱包。",
  "Wallet did not return an account.": "钱包未返回账户。",

  "VERIFIED RELEASE EVIDENCE": "已验证的发布证据",
  "Testnet performance": "测试网性能",
  "These are release-test results, not invented live market metrics. A public onchain indexer is not enabled yet.": "这些是发布测试的真实结果，不是虚构的实时市场数据。公开链上索引器尚未启用。",
  "HTTP requests": "HTTP 请求",
  "7,500 successful": "7,500 次全部成功",
  "Peak concurrency": "峰值并发",
  "5,000-request stage": "5,000 请求阶段",
  "Peak throughput": "峰值吞吐量",
  "Measured in release storm": "来自发布压力测试",
  "Real graduations": "真实毕业",
  "While web load was active": "与网页压力测试同时进行",
  "CONTRACT VERIFICATION": "合约验证",
  "Foundry suite": "Foundry 测试套件",
  "Fuzz runs": "模糊测试次数",
  "Pre-storm graduation checks": "压力测试前毕业检查",
  "Post-storm graduation checks": "压力测试后毕业检查",
  "LOAD STAGES": "负载阶段",
  "Success floor": "成功率",
  "100% observed": "实测 100%",
  "Live volume, market cap, creator counts, rewards and revenue are intentionally not displayed until Fortune has an onchain indexer that can reproduce them from public events.": "在 Fortune 上线可从公开事件复现数据的链上索引器之前，我们不会显示实时交易量、市值、创建者数量、奖励或收入。",

  "FORTUNE FORUM": "FORTUNE 社区",
  "Not live yet.": "尚未上线。",
  "The earlier forum feed was a product mockup. It has been removed from the public alpha so nobody mistakes generated posts, votes, or activity for real users.": "之前的社区内容只是产品模型，现已从公开测试版移除，避免任何人把生成的帖子、投票或活动误认为真实用户数据。",
  "Test Fortune onchain →": "链上测试 Fortune →",
  "Community features come after the onchain alpha.": "社区功能将在链上测试版之后上线。",
  "The first public release is intentionally focused on real wallet, curve, graduation, Pancake V3, and LP-lock behavior.": "首个公开版本专注于真实的钱包、曲线、毕业、Pancake V3 和 LP 锁仓功能。",

  "PROTOCOL OPERATIONS": "协议运行状态",
  "Automation state": "自动化状态",
  "Only behavior that exists in deployed contracts is shown here.": "这里仅展示已部署合约中真实存在的行为。",
  "PUBLIC ALPHA": "公开测试版",
  "What actually runs today": "当前真实运行的功能",
  "No fake dollar totals": "不展示虚假金额",
  "Permanent LP custody": "永久 LP 托管",
  "Permissionless graduation": "无需许可的毕业",
  "Retryable failure path": "可重试失败路径",
  "Seven-day reserve rescue": "七天储备救援",
  "Public automation activity index": "公开自动化活动索引",
  "Live": "已上线",
  "Pending": "待上线",

  "PORTFOLIO": "资产组合",
  "Indexer pending.": "索引器待上线。",
  "Fortune does not yet have a public portfolio indexer, so the alpha does not pretend to know your holdings, rewards, or creator earnings.": "Fortune 目前还没有公开资产组合索引器，因此测试版不会假装知道你的持仓、奖励或创建者收入。",
  "Your wallet remains the source of truth.": "你的钱包仍是最终数据来源。",
  "For now, use the public testnet page and BscScan links to inspect the test tokens and transactions you create. Portfolio aggregation will return when it is backed by real indexed chain data.": "目前请通过公开测试网页面和 BscScan 链接查看你创建的测试代币与交易。等真实链上索引数据就绪后，资产组合功能会重新上线。",

  "FORTUNE PUBLIC TESTNET REGISTRY": "FORTUNE 公开测试网资产注册表",
  "One approved alpha quote asset.": "当前只有一个已批准的测试计价资产。",
  "The public alpha does not expose the old mainnet asset catalog as if it were launchable on testnet. Only Fortune's valueless mock fUSD is enabled in the current alpha path.": "公开测试版不会把旧的主网资产目录伪装成可在测试网上使用。当前测试路径只启用 Fortune 的无价值模拟 fUSD。",
  "Use fUSD on testnet →": "在测试网使用 fUSD →",
  "TESTNET REGISTRY": "测试网注册表",
  "Real-value BSC assets are not enabled for this public alpha.": "此公开测试版未启用具有真实价值的 BSC 资产。",
  "Asset": "资产",
  "Capabilities": "功能",
  "Status": "状态",
  "quote": "计价",
  "reward": "奖励",
  "graduation": "毕业",
  "Live test contract ↗": "查看真实测试合约 ↗",

  "TOKEN MARKET PAGE": "代币市场页面",
  "Onchain indexer pending.": "链上索引器待上线。",
  "The old token page used demo market data and has been removed from the public alpha. Tokens created through the alpha are real BSC Testnet contracts and are linked directly to BscScan from the testnet flow.": "旧代币页面使用演示市场数据，现已从公开测试版移除。通过测试版创建的代币是真实 BSC 测试网合约，可从测试流程直接打开 BscScan。",
  "Create a real test launch →": "创建真实测试发行 →",
  "No synthetic chart or market-cap data.": "不展示模拟图表或市值数据。",
  "Token pages will return once curve events, graduation events and Pancake V3 swaps are indexed into a reproducible canonical chart.": "当曲线事件、毕业事件和 Pancake V3 交易被索引为可复现的标准图表后，代币页面会重新上线。",

  "FORTUNE PUBLIC API · ALPHA": "FORTUNE 公共 API · 测试版",
  "Real data or no data.": "只展示真实数据，否则不展示。",
  "Readiness and protocol configuration come from the deployed BSC Testnet stack. Market endpoints read BNB Chain directly and state the block and log coverage behind every number.": "就绪状态和协议配置来自已部署的 BSC 测试网。市场接口直接读取 BNB Chain，并注明每个数字所依据的区块和日志覆盖范围。",
  "NON-CUSTODIAL": "非托管",
  "Wallets authorize writes.": "写入操作由钱包授权。",
  "The dedicated testnet UI signs transactions in the user's wallet. Private keys never touch Fortune servers.": "专用测试网界面会在用户钱包中签署交易。私钥绝不会进入 Fortune 服务器。",
  "Preview": "预览",
  "Wallet signs": "钱包签名",
  "Chain confirms": "链上确认",
  "HONEST ALPHA ENDPOINTS": "真实测试版接口",
  "Public API": "公共 API",
  "OpenAPI JSON": "OpenAPI JSON",
  "QUICKSTART": "快速开始",
  "Check the live deployment.": "检查实时部署。",
  "INDEXER BOUNDARY": "索引器边界",
  "No fake market feed.": "不提供虚假市场数据。",
  "Prices, charts, volume, supply and holdings are read from the factory, the curves, the official pools and a bounded event log, each at a stated block. When the log window cannot cover a range, the response says so instead of filling the gap. Revenue history and social activity wait for a durable indexer.": "价格、图表、交易量、供应量和持仓均读取自工厂、曲线、官方池和有界事件日志，并各自注明区块。当日志窗口无法覆盖某个时间范围时，响应会如实说明，而不会填补空缺。收入历史和社交活动需等待持久化索引器。",
  "Markets": "市场",
  "Launch": "发行",
  "Dark mode": "深色模式",
  "Light mode": "浅色模式",
  "BNB Smart Chain wallet connected": "BNB Smart Chain 钱包已连接",
  "Wallet connected · switch network": "钱包已连接 · 请切换网络",
  "Fortune · BNB Smart Chain": "Fortune · BNB Smart Chain",
  "Real-value network · review every transaction": "真实资产网络 · 请检查每笔交易",
  "Switch network": "切换网络",
  "LIVE ONCHAIN MARKETS": "实时链上市场",
  "Fortune launches": "Fortune 发行市场",
  "Every market below is read directly from the configured Fortune factory, token, and curve contracts. No demo listings.": "下方每个市场都直接读取 Fortune 工厂、代币和曲线合约。没有演示数据。",
  "Refreshing…": "刷新中…",
  "Refresh": "刷新",
  "Launch token →": "发行代币 →",
  "Create test launch →": "创建测试发行 →",
  "BNB CHAIN MAINNET": "BNB CHAIN 主网",
  "BSC TESTNET": "BSC 测试网",
  "MARKET READ FAILED": "市场读取失败",
  "No launches on this deployment yet.": "当前部署还没有发行。",
  "The first confirmed Fortune launch will appear here directly from the factory.": "首个确认的 Fortune 发行会直接从工厂合约显示在这里。",
  "Curve price": "曲线价格",
  "Reserve": "储备",
  "Quote markets": "计价市场",
  "Graduation": "毕业",
  "Ready to graduate": "准备毕业",
  "PRODUCTION LAUNCH": "正式版发行",
  "Mainnet is not active on this deployment.": "此部署尚未启用主网。",
  "This site is currently configured for BSC Testnet. Use the public alpha flow while the audited production deployment is being prepared.": "此网站目前配置为 BSC 测试网。正式版部署完成审查前，请使用公开 Alpha 测试流程。",
  "Mainnet contracts are not fully configured.": "主网合约尚未完整配置。",
  "Fortune will not construct real-value launch transactions until the factory, registry, graduation adapter, LP locker, and approved primary quote asset are all configured.": "在工厂、资产注册表、毕业适配器、LP 锁仓和已批准的主要计价资产全部配置完成前，Fortune 不会生成真实资产发行交易。",
  "View readiness": "查看就绪状态",
  "BNB CHAIN · PRODUCTION": "BNB CHAIN · 正式版",
  "Launch a real Fortune token.": "发行真实的 Fortune 代币。",
  "Every field below becomes part of the onchain launch economics. Fortune runs a final onchain preflight before your wallet is asked to sign.": "下方每个字段都会成为链上发行参数。钱包签名前，Fortune 会进行最终链上预检查。",
  "REAL-VALUE NETWORK": "真实资产网络",
  "You are on BNB Smart Chain mainnet. Transactions spend real BNB and quote assets. Review all economics before signing.": "你正在使用 BNB Smart Chain 主网。交易会消耗真实 BNB 和计价资产。签名前请检查所有参数。",
  "Token identity": "代币信息",
  "Immutable ERC-20 name, ticker, and fixed supply.": "不可更改的 ERC-20 名称、代码和固定供应量。",
  "Total supply": "总供应量",
  "Curve economics": "曲线参数",
  "Values are USD-denominated and enforced by the deployed oracle configuration.": "数值以美元计价，并由已部署的预言机配置执行。",
  "Opening price · USD": "起始价格 · 美元",
  "Linear slope · USD per token": "线性斜率 · 每代币美元",
  "Graduation target · USD": "毕业目标 · 美元",
  "Primary quote asset": "主要计价资产",
  "Creator fee": "创建者费用",
  "Holder route": "持有人分配",
  "Buyback route": "回购分配",
  "Liquidity route": "流动性分配",
  "Protocol route": "协议分配",
  "Total trading fee": "总交易费",
  "Preflight + launch on BNB Chain →": "预检查并在 BNB Chain 发行 →",
  "Preparing launch…": "准备发行中…",
  "No transaction submitted yet.": "尚未提交交易。",
  "Transaction ↗": "交易 ↗",
  "Token ↗": "代币 ↗",
  "Open market →": "打开市场 →",
  "FORTUNE MARKET": "FORTUNE 市场",
  "Loading onchain market…": "正在加载链上市场…",
  "Market unavailable.": "市场不可用。",
  "Onchain USD oracle model": "链上美元预言机模型",
  "Graduation reserve": "毕业储备",
  "of target": "目标进度",
  "Phase": "阶段",
  "Read directly from the curve": "直接读取曲线合约",
  "Launch Shield": "Launch Shield",
  "Current buy-only opening tax": "当前仅买入的开盘税",
  "Graduation progress": "毕业进度",
  "PANCAKE V3 LIVE": "PANCAKE V3 已上线",
  "This launch has graduated. Curve buys and sells are closed; the graduation transaction created and permanently locked the Pancake V3 LP position.": "此发行已毕业。曲线买卖已关闭；毕业交易已创建并永久锁定 Pancake V3 LP 仓位。",
  "GRADUATION READY": "已准备毕业",
  "Move liquidity to Pancake V3": "将流动性转入 Pancake V3",
  "Finalization is permissionless. The adapter preflight checks the pool configuration before any reserve transfer can complete.": "任何人都可以执行毕业。适配器会先检查池配置，检查通过后才会完成储备转移。",
  "Finalize Pancake graduation →": "完成 Pancake 毕业 →",
  "Finalizing…": "毕业处理中…",
  "BUY": "买入",
  "Buy on the Fortune curve": "在 Fortune 曲线上买入",
  "Quote asset": "计价资产",
  "Amount": "数量",
  "Wallet balance": "钱包余额",
  "LAUNCH SHIELD ACTIVE": "LAUNCH SHIELD 生效中",
  "Buy UI is temporarily disabled while the opening tax is non-zero. It automatically reaches zero after the five-second launch window.": "开盘税不为零时买入暂时关闭。发行后的五秒窗口结束后会自动降为零。",
  "Approve + buy →": "授权并买入 →",
  "SELL": "卖出",
  "Sell back to the curve": "卖回曲线",
  "Approve + sell →": "授权并卖出 →",
  "Ready.": "就绪。",
  "Launch confirmed on BNB Smart Chain.": "发行已在 BNB Smart Chain 确认。",
  "Running onchain launch preflight…": "正在执行链上发行预检查…",
  "Preparing deterministic Fortune token address…": "正在准备确定性的 Fortune 代币地址…",
  "Confirm the launch transaction in your wallet.": "请在钱包中确认发行交易。",
  "Approve the quote asset in your wallet.": "请在钱包中授权计价资产。",
  "Confirm the Fortune curve buy.": "请确认 Fortune 曲线买入。",
  "Buy confirmed.": "买入已确认。",
  "Approve the Fortune token in your wallet.": "请在钱包中授权 Fortune 代币。",
  "Confirm the Fortune curve sell.": "请确认 Fortune 曲线卖出。",
  "Sell confirmed.": "卖出已确认。",
  "Confirm the Pancake V3 graduation transaction.": "请确认 Pancake V3 毕业交易。",
  "Graduation confirmed. Curve trading is closed and Pancake V3 liquidity is live.": "毕业已确认。曲线交易已关闭，Pancake V3 流动性已上线。",
  "FORTUNE · BNB SMART CHAIN": "FORTUNE · BNB SMART CHAIN",
  "Launch tokens with transparent onchain mechanics.": "用透明的链上机制发行代币。",
  "Fortune is a non-custodial BNB Chain launch framework with deterministic fixed-supply tokens, onchain curve trading, transparent fee routing, Launch Shield protection, and atomic Pancake V3 graduation.": "Fortune 是 BNB Chain 上的非托管发行框架，提供确定性固定供应代币、链上曲线交易、透明费用分配、Launch Shield 保护和原子化 Pancake V3 毕业。",
  "Launch on BNB Chain →": "在 BNB Chain 发行 →",
  "Live markets": "实时市场",
  "Real-value network. Fortune is non-custodial; always review token economics, contract addresses, and wallet prompts before signing.": "真实资产网络。Fortune 为非托管协议；签名前请检查代币参数、合约地址和钱包提示。",
  "PROTOCOL GUARANTEES": "协议保证",
  "Fixed supply": "固定供应量",
  "Atomic graduation": "原子化毕业",
  "Permanent LP lock": "永久 LP 锁仓",
  "Custody": "托管方式",
  "Non-custodial": "非托管",
  "Token supply": "代币供应量",
  "Immutable": "不可更改",
  "Deployment": "部署",
  "Configured": "已配置",
  "Incomplete": "未完成",
  "The full launch lifecycle is onchain.": "完整发行流程都在链上。",
  "Create a fixed-supply Fortune token through the production factory after an onchain launch preflight.": "通过正式版工厂，在链上预检查通过后创建固定供应量的 Fortune 代币。",
  "Buy and sell through the canonical Fortune curve using registry-approved quote assets and live oracle checks.": "使用注册表批准的计价资产和实时预言机检查，在 Fortune 标准曲线上买卖。",
  "Real BNB Chain txs": "真实 BNB Chain 交易",
  "Permissionlessly finalize eligible launches into Pancake V3 and permanently lock the resulting LP-position NFT.": "无需许可即可把符合条件的发行毕业到 Pancake V3，并永久锁定生成的 LP 仓位 NFT。",
  "PRODUCTION DEPLOYMENT": "正式版部署",
  "FORTUNE PRINCIPLES": "FORTUNE 原则",
  "Real onchain contracts": "真实链上合约",
  "Live market reads": "实时市场读取",
  "Pancake V3 graduation": "Pancake V3 毕业",
  "Transparent readiness": "透明就绪状态",
  "Mainnet release approval": "主网发布批准",
  "Governance ownership": "治理所有权",
  "Primary production quote asset": "正式版主要计价资产",
  "Mainnet launch activation": "主网发行激活",
  "Assets": "资产",
  "FORTUNE ASSET UNIVERSE": "FORTUNE 资产宇宙",
  "Launch against the BNB economy.": "面向整个 BNB 经济发行。",
  "Crypto assets, stablecoins, wrapped real-world assets, tokenized stocks, and discovery catalogs live in one place. Fortune only labels an asset “Launchable now” after the active onchain registry and oracle checks actually pass.": "加密资产、稳定币、封装现实资产、代币化股票和发现目录都集中在一个地方。只有通过当前链上注册表和预言机检查的资产，Fortune 才会标记为“现在可发行”。",
  "Build a launch →": "创建发行 →",
  "UNIVERSE-FIRST, NOT FAKE SUPPORT": "先展示完整资产宇宙，而不是伪造支持",
  "Discovery is broad. Reserve custody is strict. Any asset can be surfaced; only registry-approved, oracle-healthy assets can hold launch reserves.": "发现范围可以很广，但储备托管必须严格。任何资产都可以展示；只有注册表批准且预言机健康的资产才能作为发行储备。",
  "Launchable": "可发行",
  "BNB universe": "BNB 资产宇宙",
  "Tokenized stocks": "代币化股票",
  "Penny stocks": "低价股票",
  "China stocks": "中国股票",
  "Search symbol, name or address": "搜索代码、名称或地址",
  "Onchain source of truth": "链上真实来源",
  "Discovery catalog": "发现目录",
  "Category": "类别",
  "Address": "地址",
  "Launchable now": "现在可发行",
  "Discovery candidate": "发现候选",
  "Pairing candidate": "配对候选",
  "Discovery only": "仅供发现",
  "PANCAKE V2 LIVE": "PANCAKE V2 已上线",
  "This tax launch has graduated. Curve trading is closed; Pancake V2 liquidity is live and its fungible LP tokens are permanently locked.": "此税费代币已毕业。曲线交易已关闭；Pancake V2 流动性已上线，可替代 LP 代币已永久锁定。",
  "Move liquidity to Pancake V2": "将流动性转入 Pancake V2",
  "Finalize Pancake V2 graduation →": "完成 Pancake V2 毕业 →",
  "Finalize Pancake V3 graduation →": "完成 Pancake V3 毕业 →",
  "Confirm the Pancake V2 tax-token graduation transaction.": "请确认 Pancake V2 税费代币毕业交易。",
  "Graduation confirmed. Curve trading is closed, Pancake V2 liquidity is live, and the fungible LP position is permanently locked.": "毕业已确认。曲线交易已关闭，Pancake V2 流动性已上线，可替代 LP 仓位已永久锁定。",
  "Build the launch you actually want.": "创建你真正想要的发行。",
  "Standard tokens graduate into permanently locked Pancake V3 liquidity. Tax tokens add immutable buy/sell tax, holder rewards, buyback/burn routing and bounded anti-farmer protection before graduating into permanently locked Pancake V2 liquidity.": "标准代币毕业到永久锁定的 Pancake V3 流动性。税费代币增加不可更改的买卖税、持有人奖励、回购销毁分配和有上限的防抢池保护，然后毕业到永久锁定的 Pancake V2 流动性。",
  "Chain 97 · fUSD is valueless · use a test-only wallet. Every setting below is exercised through real testnet contracts.": "链 97 · fUSD 没有实际价值 · 请使用仅测试钱包。下方每项设置都会通过真实测试网合约执行。",
  "Launch type": "发行类型",
  "Choose the token architecture before entering economics.": "先选择代币架构，再设置经济参数。",
  "Standard": "标准",
  "0% transfer tax · Pancake V3": "0% 转账税 · Pancake V3",
  "Tax Token": "税费代币",
  "Immutable tax · dividends · anti-farmer · Pancake V2": "不可变税费 · 分红 · 防抢池 · Pancake V2",
  "Tax stack awaits one-time public deployment": "税费系统等待一次性公开部署",
  "tBNB pays gas. fUSD is the valueless launch quote.": "tBNB 用于支付 Gas。fUSD 是无价值的测试计价资产。",
  "Faucet 1,000 fUSD": "领取 1,000 fUSD",
  "Fixed supply. No post-launch mint or blacklist.": "固定供应量。发行后不能增发，也没有黑名单。",
  "Creator first purchase": "创建者首次买入",
  "Optional. Approve fUSD once, then Fortune deploys the token and executes your first curve buy inside the same transaction.": "可选。先授权一次 fUSD，然后 Fortune 会在同一笔交易中部署代币并执行你的首次曲线买入。",
  "Initial creator purchase · fUSD": "创建者首次买入 · fUSD",
  "Tax + anti-farmer protection": "税费 + 防抢池保护",
  "Immutable at launch. Tax cannot later be increased and the protection window cannot be extended.": "发行时即永久确定。税率之后不能提高，保护期也不能延长。",
  "Buy tax · %": "买入税 · %",
  "Sell tax · %": "卖出税 · %",
  "Anti-farmer protection · days": "防抢池保护 · 天",
  "0 disables it. During the window, recognized competing pools from approved AMM factories cannot be used.": "设为 0 即关闭。在保护期内，来自已批准 AMM 工厂的已识别竞争池不能使用。",
  "Minimum dividend balance · tokens": "最低分红持仓 · 代币",
  "Tax allocation": "税费分配",
  "Every percent is committed onchain. Total must equal 100%.": "每一个百分比都会写入链上。总计必须等于 100%。",
  "Creator": "创建者",
  "Direct burn": "直接销毁",
  "Holder dividends": "持有人分红",
  "Buyback + burn": "回购 + 销毁",
  "Liquidity": "流动性",
  "Community treasury": "社区金库",
  "Protocol": "协议",
  "Community treasury recipient · optional": "社区金库接收地址 · 可选",
  "Defaults to connected creator wallet": "默认使用已连接的创建者钱包",
  "Links": "链接",
  "Optional public metadata for the token profile.": "代币资料页的可选公开信息。",
  "Website": "网站",
  "X / Twitter": "X / Twitter",
  "Telegram": "Telegram",
  "GitHub": "GitHub",
  "YouTube": "YouTube",
  "DeBox": "DeBox",
  "Immutable launch preview": "不可变发行预览",
  "Review before signing.": "签名前请确认。",
  "Architecture": "架构",
  "Supply": "供应量",
  "Quote": "计价资产",
  "Buy / sell tax": "买入 / 卖出税",
  "Anti-farmer": "防抢池",
  "CURVE → PANCAKE": "曲线 → PANCAKE",
  "Complete the lifecycle": "完成完整生命周期",
  "Graduation DEX": "毕业 DEX",
  "LP custody": "LP 托管",
  "Permanently locked": "永久锁定",
  "The confirmed token and curve addresses appear here.": "确认后的代币和曲线地址会显示在这里。",
  "Standard factory": "标准工厂",
  "Tax factory": "税费代币工厂",
  "Pool registry": "池注册表",
  "V3 graduation adapter": "V3 毕业适配器",
  "V3 LP locker": "V3 LP 锁仓",
  "V2 tax adapter": "V2 税费适配器",
  "V2 LP locker": "V2 LP 锁仓",
  "Launch architecture": "发行架构",
  "Choose the immutable token model.": "选择不可变的代币模型。",
  "0% transfer tax · Pancake V3 · permanent NFT LP lock": "0% 转账税 · Pancake V3 · 永久 NFT LP 锁仓",
  "Tax + dividends + anti-farmer · Pancake V2": "税费 + 分红 + 防抢池 · Pancake V2",
  "Available after the production tax stack passes release gates": "正式版税费系统通过发布检查后开放",
  "Payment asset": "支付资产",
  "The picker is sourced from the live Fortune registry, not a hard-coded token list.": "选择器直接来自 Fortune 实时注册表，而不是写死的代币列表。",
  "Search the launchable asset universe": "搜索可发行资产宇宙",
  "Browse full universe": "浏览完整资产宇宙",
  "ASSET READ FAILED": "资产读取失败",
  "Creator first purchase · quote": "创建者首次买入 · 计价资产",
  "USD-denominated values enforced by Fortune's live oracle.": "以美元计价的参数由 Fortune 实时预言机执行。",
  "Selected quote": "已选计价资产",
  "Choose an asset above": "请在上方选择资产",
  "Tax + anti-farmer": "税费 + 防抢池",
  "Immutable at launch. Rates cannot later be raised.": "发行时永久确定。税率之后不能提高。",
  "Anti-farmer · days": "防抢池 · 天",
  "Minimum dividend balance": "最低分红持仓",
  "Total must equal exactly 100%.": "总计必须严格等于 100%。",
  "Optional public token profile links.": "可选的公开代币资料链接。",
  "Running tax-token launch preflight…": "正在执行税费代币发行预检查…",
  "The production tax-token stack is not activated.": "正式版税费代币系统尚未激活。",
  "Choose a launchable payment asset.": "请选择可发行的支付资产。",
  "Tax allocation must total exactly 100%.": "税费分配必须严格合计为 100%。",
  "Buy and sell tax must each be between 0% and 10%, with at least one non-zero.": "买入税和卖出税都必须在 0% 到 10% 之间，并且至少一个不为 0。",
  "Anti-farmer duration must be 0–365 days.": "防抢池期限必须为 0–365 天。",
  "Approve the creator purchase, then confirm the atomic launch + first buy.": "请先授权创建者买入，然后确认原子化发行 + 首次买入。",
  "Approve the creator purchase, then confirm the atomic tax launch + first buy.": "请先授权创建者买入，然后确认原子化税费代币发行 + 首次买入。",
  "Confirm the tax-token launch transaction.": "请确认税费代币发行交易。",

  // Redesigned shell, home and launch surfaces.
  "Home": "首页",
  "Explore": "探索",
  "Burns": "销毁",
  "Rewards": "奖励",
  "Stats": "数据",
  "Docs": "文档",
  "Search": "搜索",
  "Profile": "个人主页",
  "Primary": "主导航",
  "Mobile": "移动导航",
  "Open menu": "打开菜单",
  "Close menu": "关闭菜单",
  "Language": "语言",
  "Public BSC Testnet alpha": "BSC 公开测试版",
  "Launches open": "发行已开放",
  "Launches paused": "发行已暂停",
  "LET'S MAKE SOMETHING FUN.": "一起做点有趣的事。",
  "Meme coins,": "Meme 币，",
  "paired with the BNB economy.": "与整个 BNB 经济配对。",
  "Launch against BNB, stablecoins, BNB-native assets, tokenized stocks, or eventually any compatible BEP-20 that passes Fortune's checks.": "可与 BNB、稳定币、BNB 原生资产、代币化股票配对发行，未来还将支持任何通过 Fortune 检查的兼容 BEP-20。",
  "Launch a token": "发行代币",
  "Explore tokens": "探索代币",
  "Every Standard launch": "每个 Standard 发行",
  "No mint or blacklist": "无增发、无黑名单",
  "0x…fe address": "0x…fe 地址",
  "CREATE2 vanity suffix": "CREATE2 靓号后缀",
  "Locked liquidity": "锁定流动性",
  "Pancake V3 LP, forever": "Pancake V3 LP 永久锁定",
  "Public BSC Testnet alpha. Mainnet remains fail-closed until the production release gates are complete.": "BSC 公开测试版。在正式发布闸门全部完成前，主网保持关闭。",
  "Real-value BNB Chain deployment. Availability is constrained by the reviewed onchain registry and release gates.": "真实资产的 BNB Chain 部署。可用范围受已审核的链上注册表和发布闸门限制。",
  "FORTUNE ON BNB": "BNB 上的 FORTUNE",
  "Make your own luck.": "好运，自己创造。",
  "THREE RULES": "三条规则",
  "The whole product should fit in your head.": "整个产品，一目了然。",
  "V2 IN REVIEW": "V2 审核中",
  "BNB NATIVE": "BNB 原生",
  "No dumping": "不砸盘",
  "Burn + Rewards v2 is being built so Fortune never sells the launch-token fee stream to fund rewards. Token-side fees burn. Pair-asset fees stay pair assets.": "Burn + Rewards v2 的设计确保 Fortune 永远不会出售发行代币的手续费来支付奖励。代币侧手续费直接销毁，配对资产侧手续费保持为配对资产。",
  "No reward-funded sell pressure.": "没有为支付奖励而产生的抛压。",
  "Holders get paid": "持有人获得回报",
  "The target Burn + Rewards market pays holder rewards in the pair asset itself — BNB, a stablecoin, a stock representation, or another reviewed BNB asset — without selling the meme coin first.": "目标中的 Burn + Rewards 市场直接以配对资产向持有人发放奖励——BNB、稳定币、股票代币或其他经审核的 BNB 资产——无需先卖出 Meme 币。",
  "Rewards in what the token trades against.": "奖励就是代币的配对资产。",
  "Pair with anything": "万物皆可配对",
  "Start with BNB. Expand into USDT/USDC, BTCB, ETH, CAKE, tokenized stocks/RWAs and eventually compatibility-checked BEP-20s.": "从 BNB 开始，逐步扩展到 USDT/USDC、BTCB、ETH、CAKE、代币化股票/RWA，最终支持通过兼容性检查的 BEP-20。",
  "The BNB economy becomes the pair menu.": "整个 BNB 经济都是你的配对菜单。",
  "HOW A LAUNCH WORKS": "发行流程",
  "Five short steps, checked onchain before you sign.": "五个简短步骤，签名前全部经过链上检查。",
  "Start a launch →": "开始发行 →",
  "Name it": "命名",
  "Name, ticker and a square image. These details are visible to everyone.": "名称、代码和一张方形图片。这些信息对所有人可见。",
  "Pick Standard": "选择 Standard",
  "Fixed supply with Pancake V3 graduation. Burn + Rewards stays in research.": "固定供应量，毕业至 Pancake V3。Burn + Rewards 仍在研究中。",
  "Choose a pair": "选择配对资产",
  "Only live registry-approved assets are selectable.": "只能选择链上注册表已批准的资产。",
  "Optional first buy": "可选首次买入",
  "Simulated with a minimum token output before it is submitted.": "提交前会模拟交易并设置最低代币输出。",
  "Review + launch": "检查并发行",
  "Fortune repeats the onchain preflight before your wallet signs.": "钱包签名前，Fortune 会再次执行链上预检查。",
  "FORTUNE LAUNCH SHIELD": "FORTUNE 发行护盾",
  "Snipers meet a shield in the first seconds.": "开盘最初几秒，狙击者会撞上护盾。",
  "Every Fortune curve opens with protocol-level anti-sniper protection. Shield proceeds reinforce liquidity instead of paying the creator.": "每条 Fortune 曲线开盘时都带有协议级防狙击保护。护盾收入用于加强流动性，而不是支付给创建者。",
  "How launches work →": "了解发行机制 →",
  "Opening buy tax": "开盘买入税",
  "Decays over the first five seconds": "在最初五秒内递减",
  "Per-wallet cap": "单钱包上限",
  "Cumulative buys in the first 15 seconds": "前 15 秒内的累计买入",
  "Exemptions": "豁免",
  "None": "无",
  "Creator wallets pay the shield too": "创建者钱包同样适用护盾",
  "Stuck launch rescue": "卡住发行的救援",
  "7 days": "7 天",
  "Then holders can trigger a pro-rata reserve rescue": "之后持有人可触发按比例的储备救援",
  "WHY BNB IS DIFFERENT": "为什么 BNB 与众不同",
  "A much larger pair universe than a meme-only launchpad.": "比纯 Meme 发行平台大得多的配对宇宙。",
  "Listing a category is not approval to launch against every asset in it. Fortune requires an exact BSC contract, compatible token behavior, oracle policy and graduation readiness before a pair becomes launchable.": "列出某个类别并不代表其中每个资产都可用于发行。配对资产可发行之前，Fortune 要求确切的 BSC 合约、兼容的代币行为、预言机策略以及毕业就绪。",
  "Pair registry →": "配对注册表 →",
  "BNB + majors": "BNB + 主流币",
  "WBNB first · BTCB / ETH expansion": "WBNB 优先 · 扩展至 BTCB / ETH",
  "Stablecoins": "稳定币",
  "USDT · USDC · FDUSD candidates": "USDT · USDC · FDUSD 候选",
  "CAKE and reviewed BEP-20 assets": "CAKE 及经审核的 BEP-20 资产",
  "xStocks · bStocks · eligibility-gated": "xStocks · bStocks · 需资格审核",
  "Any BEP-20": "任意 BEP-20",
  "Compatibility + oracle + liquidity review": "兼容性 + 预言机 + 流动性审核",
  "PUBLIC PROOF": "公开证明",
  "Burns, rewards and protocol stats belong in public ledgers.": "销毁、奖励和协议数据都应记录在公开账本中。",
  "Burn routes backed by public transaction evidence.": "由公开交易证据支撑的销毁路径。",
  "Pair-asset holder claims with a public ledger.": "以配对资产领取的持有人奖励，配有公开账本。",
  "Exact launch counts read from the factories.": "直接从工厂合约读取的精确发行数量。",
  "System status": "系统状态",
  "Live RPC, contract and release-gate checks.": "实时 RPC、合约和发布闸门检查。",
  "The same public data Fortune uses.": "与 Fortune 使用的相同公开数据。",
  "Try the full launch flow with valueless test assets first.": "先用无价值的测试资产体验完整发行流程。",
  "Every launch is checked onchain before your wallet signs.": "每次发行在钱包签名前都会经过链上检查。",
  "Testnet lab": "测试网实验室",
  "BNB CHAIN · CREATE": "BNB CHAIN · 创建",
  "Name it, choose a reviewed pair, then inspect the exact launch before your wallet signs.": "命名代币，选择经审核的配对资产，并在钱包签名前检查完整的发行参数。",
  "Launch steps": "发行步骤",
  "Name + ticker + image": "名称 + 代码 + 图片",
  "Pair asset": "配对资产",
  "First buy": "首次买入",
  "LIVE PREVIEW": "实时预览",
  "Your token": "你的代币",
  "Launch preview": "发行预览",
  "Pair": "配对",
  "Fee route": "手续费分配",
  "0.5% creator · 0.5% protocol": "0.5% 创建者 · 0.5% 协议",
  "Pancake V3 · locked LP": "Pancake V3 · 锁定 LP",
  "Token address": "代币地址",
  "Ends in fe": "以 fe 结尾",
  "Edit details": "编辑信息",
  "CONTENTS": "目录",
  "Contents": "目录",

  // Launch flow and page states.
  "PUBLIC BSC TESTNET ALPHA": "BSC 公开测试版",
  "MAINNET RELEASE GATED": "主网发布受闸门限制",
  "Create a valueless testnet Standard launch here. Use the testnet lab for the mock-asset faucet and detailed research controls.": "在这里创建无价值的测试网 Standard 发行。模拟资产水龙头和详细研究控制请前往测试网实验室。",
  "The Standard launch button unlocks only after all onchain and release checks pass.": "只有所有链上检查和发布检查通过后，Standard 发行按钮才会解锁。",
  "These details are visible to everyone.": "这些信息对所有人可见。",
  "Your token name": "你的代币名称",
  "Image URL or IPFS URI": "图片 URL 或 IPFS URI",
  "Host a square image publicly first. Fortune records this link immutably at launch; image upload hosting is still being prepared.": "请先公开托管一张方形图片。Fortune 会在发行时永久记录此链接；图片上传托管功能仍在准备中。",
  "Standard is the only mainnet candidate.": "Standard 是唯一的主网候选。",
  "Fixed supply · Pancake V3 · permanently locked LP position": "固定供应量 · Pancake V3 · 永久锁定 LP 仓位",
  "Pair-asset holder claims via Infinity hook · v2 in research": "通过 Infinity hook 以配对资产领取持有人奖励 · v2 研究中",
  "Separate testnet research and audit required": "需要单独的测试网研究和审计",
  "Pair policy →": "配对政策 →",
  "Search approved BNB assets": "搜索已批准的 BNB 资产",
  "Search approved pair assets": "搜索已批准的配对资产",
  "No approved pair found.": "未找到已批准的配对资产。",
  "Asset discovery alone does not mean an asset is safe to pair.": "被发现并不代表该资产可以安全配对。",
  "Zero means launch without a creator purchase.": "填 0 表示发行时不进行创建者买入。",
  "Amount in": "金额 ·",
  "pair asset": "配对资产",
  "The Launch Shield charges up to 99% on buys in the first five seconds, including a creator first buy. Fortune simulates the atomic transaction and sets a minimum token output before submitting it.": "Launch Shield 会在开盘前五秒内对买入收取最高 99% 的税，创建者首次买入也不例外。Fortune 会先模拟原子交易，并在提交前设置最低代币输出。",
  "Advanced · curve economics and profile links": "高级 · 曲线参数和资料链接",
  "These research defaults mirror the mainnet fork rehearsal. They remain subject to independent economic review and onchain preflight.": "这些研究默认值与主网分叉演练一致，仍需经过独立经济审查和链上预检查。",
  "Total token supply": "代币总供应量",
  "Slope · USD per token": "斜率 · 每代币美元",
  "Community treasury · optional": "社区金库 · 可选",
  "Defaults to creator wallet": "默认使用创建者钱包",
  "Website · optional": "网站 · 可选",
  "X · optional": "X · 可选",
  "Telegram · optional": "Telegram · 可选",
  "GitHub · optional": "GitHub · 可选",
  "YouTube · optional": "YouTube · 可选",
  "DeBox · optional": "DeBox · 可选",
  "Description · optional": "简介 · 可选",
  "Review and launch": "检查并发行",
  "Confirm the immutable details before signing.": "签名前请确认这些不可更改的信息。",
  "Review launch →": "检查发行 →",
  "STATUS": "状态",
  "Supply / target": "供应量 / 目标",
  "Creator first buy": "创建者首次买入",
  "Liquidity / mode": "流动性 / 模式",
  "Pancake V3 · Standard · fixed metadata": "Pancake V3 · Standard · 固定元数据",
  "Image URI": "图片 URI",
  "An approved pair and wallet transaction are required. Fortune checks the current chain, release state and onchain preflight again before any submission.": "需要已批准的配对资产和钱包交易。每次提交前，Fortune 都会再次检查当前链、发布状态和链上预检查。",
  "Checking launch…": "正在检查发行…",
  "Confirm in wallet →": "在钱包中确认 →",
  "Launch on BSC Testnet →": "在 BSC 测试网发行 →",
  "Launch paused": "发行已暂停",
  "The release manifest and live contract checks must pass before mainnet transactions unlock.": "主网交易解锁前，发布清单和实时合约检查必须通过。",
  "Need valueless fUSD or tBNB gas?": "需要无价值的 fUSD 或 tBNB Gas？",
  "Open the testnet lab and faucet →": "打开测试网实验室和水龙头 →",
  "That Fortune market was not found.": "未找到该 Fortune 市场。",
  "It may not be indexed yet, or the address/link may be incorrect.": "它可能尚未被索引，或者地址/链接有误。",
  "Back to Explore": "返回探索",
  "DEGRADED MODE": "降级模式",
  "This part of Fortune hit an error.": "Fortune 的这一部分出现了错误。",
  "The rest of the app can remain available. Retry this view without reconnecting your wallet or resubmitting a transaction.": "应用的其余部分仍可使用。无需重新连接钱包或重新提交交易，直接重试此视图即可。",
  "Retry": "重试",
  "Loading market data…": "正在加载市场数据…",
  "Core pages render independently from optional market-data providers.": "核心页面独立渲染，不依赖可选的市场数据提供方。",

  // Cinematic home: hero kicker, Q&A and closing quote.
  "BNB Smart Chain launchpad": "BNB Smart Chain 发行平台",
  "BEFORE YOU LAUNCH": "发行之前",
  "System": "系统",
  "Make your own luck,": "好运，自己创造，",
  "then let the chain prove it.": "再交给链上来证明。",
  "What is Fortune?": "Fortune 是什么？",
  "A BNB Smart Chain launchpad for meme coins. Name a token, choose a reviewed pair asset, optionally make the first buy, and launch a fixed-supply token on Fortune's curve.": "一个面向 Meme 币的 BNB Smart Chain 发行平台。为代币命名，选择经审核的配对资产，可选首次买入，然后在 Fortune 曲线上发行固定供应量的代币。",
  "Can I use real money yet?": "现在可以使用真实资金吗？",
  "No. Fortune is a public alpha on BSC Testnet with valueless test assets. The contracts are pre-audit, and mainnet stays disabled until independent review and every release gate pass.": "不可以。Fortune 目前是 BSC 测试网上的公开测试版，只使用无价值的测试资产。合约尚未完成审计，在独立审查和所有发布闸门通过之前，主网保持关闭。",
  "What does the Launch Shield do?": "Launch Shield 有什么作用？",
  "Every curve opens with a 99% buy tax that decays to zero within five seconds, plus a 2% per-wallet cap for the first 15 seconds. Creators are not exempt, and shield proceeds reinforce liquidity.": "每条曲线开盘时的买入税为 99%，并在五秒内递减至零；前 15 秒内每个钱包最多买入 2%。创建者不享有豁免，护盾收入用于加强流动性。",
  "What happens at graduation?": "毕业时会发生什么？",
  "Anyone can finalize graduation once a curve reaches its target. Standard launches move into Pancake V3 and the LP position is locked in Fortune's locker for good. Failed graduations stay retryable, and after seven days holders can trigger a pro-rata reserve rescue.": "曲线达到目标后，任何人都可以完成毕业。Standard 发行会迁移到 Pancake V3，LP 仓位被永久锁定在 Fortune 锁仓合约中。毕业失败可以重试；七天后，持有人可以触发按比例的储备救援。",
  "Which assets can I pair with?": "可以与哪些资产配对？",
  "Only assets approved in the onchain registry. The Standard mainnet candidate is pinned to WBNB; stablecoins, BNB majors, DeFi tokens and tokenized stocks arrive in separate, reviewed releases.": "只能使用链上注册表批准的资产。Standard 主网候选固定为 WBNB；稳定币、BNB 主流币、DeFi 代币和代币化股票会在单独审核的版本中陆续加入。",
  "Is Burn + Rewards live?": "Burn + Rewards 上线了吗？",
  "Not yet. Burn + Rewards v2 is research: token-side fees would burn and holders would be paid in the pair asset without selling the meme coin. It has its own audit boundary and no real-value deployment.": "还没有。Burn + Rewards v2 仍在研究中：代币侧手续费将被销毁，持有人将以配对资产获得奖励，而无需卖出 Meme 币。它有独立的审计边界，目前没有真实资产部署。",

  // Entry disclaimer and the full disclaimer in Docs.
  "Network status": "网络状态",
  "Before you enter Fortune": "进入 Fortune 之前",
  "Please read and confirm before continuing.": "请阅读并确认后再继续。",
  "Trading risk": "交易风险",
  "Meme coins are speculative. Prices can swing sharply, liquidity can disappear and you can lose everything you trade.": "Meme 币具有投机性。价格可能剧烈波动，流动性可能消失，你可能损失全部交易资金。",
  "Not financial advice": "非投资建议",
  "Fortune provides software and onchain data, not investment advice. Listings, rankings and charts are not endorsements, and no return is promised.": "Fortune 提供软件和链上数据，而非投资建议。上架、排名和图表均不构成背书，也不承诺任何回报。",
  "Your responsibility": "你的责任",
  "Check every token, approval and transaction in your wallet. Contracts can fail, scams exist and confirmed transactions cannot be reversed. Network fees apply.": "请在钱包中核对每个代币、每次授权和每笔交易。合约可能出错，骗局确实存在，已确认的交易无法撤销。交易需支付网络费用。",
  "Public testnet alpha": "公开测试网 Alpha",
  "Fortune currently runs on BSC Testnet with valueless test assets. The contracts are pre-audit and mainnet is disabled.": "Fortune 目前运行在 BSC 测试网上，使用无价值的测试资产。合约尚未审计，主网处于停用状态。",
  "I understand these risks and take responsibility for my own transactions.": "我了解上述风险，并对自己的交易负责。",
  "Continue to Fortune →": "继续进入 Fortune →",
  "Read the full disclaimer ↗": "阅读完整免责声明 ↗",
  "Risk disclaimer": "风险免责声明",
  "RISK DISCLAIMER": "风险免责声明",
  "Read this before you trade": "交易前请先阅读",
  "Eligibility": "使用资格",
  "Eligibility and jurisdiction terms will come from Fortune's legal review, which is still an open mainnet release gate. Confirming this disclaimer does not replace that review.": "使用资格和适用司法辖区条款将由 Fortune 的法律审查确定，该审查仍是尚未完成的主网发布关卡。确认本免责声明并不能替代该审查。",
  "Data can lag": "数据可能延迟",

  // Explore sorting, market panel, pair assets and trades.
  "Sort launches": "排序发行",
  "Newest": "最新",
  "24H Volume": "24小时交易量",
  "Trending": "热门",
  "Highest Market Cap": "最高市值",
  "Newest launches first, straight from the Fortune factories.": "最新发行排在最前，直接读取自 Fortune 工厂合约。",
  "Price × total supply. Graduated tokens are priced from their official locked Pancake pools.": "价格 × 总供应量。已毕业代币按其官方锁定的 Pancake 池定价。",
  "Fortune curve trades plus official Pancake pool swaps over the last 24 hours.": "过去 24 小时内 Fortune 曲线交易与官方 Pancake 池兑换之和。",
  "Most trades in the last 6 hours, then 6-hour volume.": "按过去 6 小时的交易笔数排序，其次按 6 小时交易量。",
  "Price": "价格",
  "Market cap": "市值",
  "Volume · 24h": "交易量 · 24小时",
  "Trades · 6h": "交易笔数 · 6小时",
  "Pool liquidity": "池子流动性",
  "Show more launches": "显示更多发行",
  "Loading…": "加载中…",
  "Reading onchain launches…": "正在读取链上发行…",
  "Onchain launch count unavailable.": "链上发行数量暂不可用。",
  "PRICE CHART": "价格图表",
  "Fortune curve spot price": "Fortune 曲线现价",
  "Pancake V3 official pool price": "Pancake V3 官方池价格",
  "Pancake V2 official pool price": "Pancake V2 官方池价格",
  "Chart source": "图表来源",
  "Chart range": "图表范围",
  "Reading trades and pool state from BNB Chain…": "正在从 BNB Chain 读取交易和池子状态…",
  "Market data unavailable.": "市场数据暂不可用。",
  "Trade history is unavailable right now; price and liquidity are live contract reads.": "交易历史暂不可用；价格和流动性为实时合约读取。",
  "Trade history is unavailable right now.": "交易历史暂不可用。",
  "Price × total supply": "价格 × 总供应量",
  "Official locked pools": "官方锁定池",
  "Curve reserve": "曲线储备",
  "Accounted onchain": "链上记账",
  "24h volume": "24小时交易量",
  "Needs 24h of trade history": "需要 24 小时的交易历史",
  "No recent trades": "近期无交易",
  "PAIR ASSETS": "配对资产",
  "Paired with one asset": "与一种资产配对",
  "Each pair asset now trades in its own official Pancake pool, holding Fortune's permanently locked liquidity.": "每种配对资产现在都在各自的官方 Pancake 池中交易，池中是 Fortune 永久锁定的流动性。",
  "Buyers pay in these assets on the Fortune curve. At graduation each one gets its own Pancake pool.": "买家在 Fortune 曲线上使用这些资产付款。毕业时，每种资产都会获得自己的 Pancake 池。",
  "Graduation weight": "毕业权重",
  "Asset price": "资产价格",
  "Pair-asset holder rewards are in development (Burn + Rewards v2). Standard launches do not pay holder rewards.": "配对资产持有人奖励仍在开发中（Burn + Rewards v2）。Standard 发行不向持有人支付奖励。",
  "RECENT TRADES": "最近交易",
  "Time": "时间",
  "Side": "方向",
  "Value": "价值",
  "Tokens": "代币数量",
  "Venue": "交易场所",
  "Transaction": "交易",
  "Buy": "买入",
  "Sell": "卖出",
  "Fortune curve": "Fortune 曲线",
  "View transaction on BscScan": "在 BscScan 查看交易",
  "Prices, charts, volume and rankings come from public BNB Chain RPC endpoints and can be delayed, incomplete or briefly unavailable. Confirm amounts and addresses in your wallet before you sign.": "价格、图表、交易量和排名来自公共 BNB Chain RPC 节点，可能延迟、不完整或短暂不可用。签名前请在钱包中确认金额和地址。",
  "Featured": "精选",
  "Crypto": "加密资产",
  "Stocks": "股票",
  "RWA": "现实资产",
  "Pre-IPO": "IPO 前",
  "New": "新上线",
  "Search pairs by name, ticker or contract": "按名称、代码或合约搜索配对资产",
  "Search name, ticker or contract": "搜索名称、代码或合约",
  "Tokenized stocks trade onchain 24/7. Outside US market hours their price can drift from the listed share and gap at the next open.": "代币化股票在链上全天候交易。美股交易时段之外，其价格可能偏离上市股票，并在下次开盘时跳空。",
  "Stock issuer": "股票发行方",
  "All issuers": "全部发行方",
  "Stock type": "股票类型",
  "All types": "全部类型",
  "ETFs": "ETF",
  "Pre-IPO tokens are issuer-structured claims, not shares. Fortune lists what exists on BNB Chain and shows other venues as price references.": "IPO 前代币是发行方设计的权益主张，而不是股份。Fortune 列出 BNB Chain 上已有的代币，其他交易场所仅作为价格参考。",
  "PAIR UNIVERSE UNAVAILABLE": "配对资产库暂不可用",
  "The pair universe could not load. Registry-approved pairs are still checked when you launch.": "配对资产库无法加载。发行时仍会检查注册表批准的配对资产。",
  "Try again": "重试",
  "Loading pairs": "正在加载配对资产",
  "No pair matches.": "没有匹配的配对资产。",
  "Try a ticker such as NVDA, a company name or a contract address.": "试试 NVDA 这样的代码、公司名称或合约地址。",
  "Selected": "已选择",
  "Reference": "参考",
  "Hot": "热门",
  "Show more": "显示更多",
  "Eligibility check": "资格检查",
  "Eligibility check passed": "资格检查通过",
  "Price reference only": "仅作价格参考",
  "Not available for Fortune launches yet": "暂不可用于 Fortune 发行",
  "Reload the page to refresh this form's approved pairs.": "请刷新页面以更新此表单的已批准配对资产。",
  "Eligibility is checked again onchain, with a fresh oracle price, before your wallet signs.": "在钱包签名前，会使用最新的预言机价格在链上再次检查资格。",
  "Lives on BNB Smart Chain mainnet. This testnet alpha pairs only with its own valueless test assets.": "该资产位于 BNB Smart Chain 主网。此测试网 alpha 版只能与其自有的无价值测试资产配对。",
  "Not approved in Fortune's onchain Asset Registry.": "未获 Fortune 链上资产注册表批准。",
  "Tokenized stocks, funds, commodities and pre-IPO tokens are outside the mainnet v1 asset policy.": "代币化股票、基金、大宗商品和 IPO 前代币不在主网 v1 资产政策范围内。",
  "Balances follow a share multiplier. Fortune needs a non-rebasing wrapper before pairing.": "余额随股份乘数变化。配对前 Fortune 需要一个不会变基的封装代币。",
  "Standard launches on mainnet v1 pair with WBNB only.": "主网 v1 的 Standard 发行只能与 WBNB 配对。",
  "An external perpetual market, not a BEP-20 token. Shown as a price reference.": "这是外部永续合约市场，不是 BEP-20 代币，仅作为价格参考。",
  "Not deployed on BNB Chain. Shown as a price reference.": "未部署在 BNB Chain 上，仅作为价格参考。",
  "The registry has this asset switched off.": "注册表已停用该资产。",
  "Its price oracle is stale or unhealthy right now.": "其价格预言机当前已过期或不健康。",
  "Not enabled as a payment asset.": "未启用为支付资产。",
  "Not enabled for graduation pools.": "未启用毕业池。",
  "Unsupported network.": "不支持的网络。",
  "Contract": "合约",
  "Copy": "复制",
  "Copied": "已复制",
  "Decimals": "精度",
  "Underlying": "标的",
  "Issuer controls": "发行方权限",
  "Upgradeable contract": "可升级合约",
  "Pause switch": "暂停开关",
  "Share multiplier": "股份乘数",
  "None detected by Fortune's probe": "Fortune 探测未发现",
  "Underlying market": "标的市场",
  "Leveraged or inverse fund: its value resets daily and can fall much faster than the index it tracks.": "杠杆或反向基金：其价值每日重置，下跌速度可能远快于所跟踪的指数。",
  "OpenAI and Anthropic have said share transfers to SPVs without their approval are void, and that tokens selling that exposure may have no value.": "OpenAI 和 Anthropic 表示，未经其批准向 SPV 转让股份无效，出售此类敞口的代币可能毫无价值。",
  "Anthropic and OpenAI have said share transfers to SPVs without their approval are void, and that tokens selling that exposure may have no value.": "Anthropic 和 OpenAI 表示，未经其批准向 SPV 转让股份无效，出售此类敞口的代币可能毫无价值。",
  "SPV tokens give contractual or indirect economic exposure only: no shares, voting, dividend or information rights in the company.": "SPV 代币仅提供合同性或间接的经济敞口：不享有公司的股份、投票权、分红权或知情权。",
  "Source ↗": "来源 ↗",
  "FORTUNE PAIR UNIVERSE": "FORTUNE 配对资产库",
  "Pair with the whole BNB economy.": "与整个 BNB 经济配对。",
  "Tokenized stocks, funds, gold and pre-IPO tokens on BNB Smart Chain, next to the majors, with live prices, issuer controls and US market hours. A launch can use an asset only after Fortune's onchain registry and oracle checks pass.": "BNB Smart Chain 上的代币化股票、基金、黄金和 IPO 前代币，与主流资产并列展示，附实时价格、发行方权限和美股交易时间。只有通过 Fortune 链上注册表和预言机检查后，资产才能用于发行。",
  "Pair universe": "配对资产库",
  "More research catalogs · NASDAQ penny stocks and China stocks": "更多研究目录 · 纳斯达克低价股与中国股票",
  "Tickers without a recognized BNB Chain token stay discoverable but are not pairable. A ticker alone is never enough.": "没有公认 BNB Chain 代币的股票代码仍可被发现，但不能配对。仅有股票代码永远不够。",
  "NASDAQ penny stocks": "纳斯达克低价股",
  "Search research catalog": "搜索研究目录",
  "CATALOG READ FAILED": "目录读取失败",
  "Stocks & pairs": "股票与配对资产",
  "Browse every stock, fund, gold and pre-IPO token on BNB Chain. Only registry-approved assets can hold launch reserves.": "浏览 BNB Chain 上的所有股票、基金、黄金和 IPO 前代币。只有注册表批准的资产才能作为发行储备。",
  "SUPPLY": "供应量",
  "Where the supply sits": "供应量分布",
  "Balances of the curve, the creator, Fortune's vaults, the official pools and burn addresses, read onchain at the same block. Everyone else covers every other wallet and contract.": "曲线、创建者、Fortune 金库、官方池和销毁地址的余额，均在同一区块链上读取。其他所有地址涵盖其余全部钱包和合约。",
  "Watchlist": "关注列表",
  "Launches you starred. Saved only in this browser.": "你标星的发行。仅保存在此浏览器中。",
  "Your watchlist is empty.": "你的关注列表是空的。",
  "Tap the star on any launch to follow it here. The list stays in this browser.": "点击任意发行上的星标即可在此关注。列表保存在此浏览器中。",
  "Post on X ↗": "分享到 X ↗",
  "Telegram ↗": "Telegram ↗",
  "Copy link": "复制链接",
  "Link copied": "链接已复制",
  "Share…": "分享…",
  "Share this launch": "分享此发行",
  "Share your launch": "分享你的发行",
  "HOLDINGS": "持仓",
  "Your Fortune tokens": "你的 Fortune 代币",
  "Fortune tokens held": "持有的 Fortune 代币",
  "Total value": "总价值",
  "Positions": "持仓数",
  "Launched": "已发行",
  "Reading balances from BNB Chain…": "正在从 BNB Chain 读取余额…",
  "Balances are unavailable right now.": "暂时无法读取余额。",
  "No Fortune tokens in this wallet yet.": "这个钱包还没有 Fortune 代币。",
  "This address holds no Fortune tokens.": "该地址未持有 Fortune 代币。",
  "Balances cover every launch recorded by the Fortune factory.": "余额覆盖 Fortune 工厂记录的每一次发行。",
  "Explore launches →": "探索发行 →",
  "Balance": "余额",
  "Trade →": "交易 →",
  "Your Fortune bag.": "你的 Fortune 持仓。",
  "Wallet holdings.": "钱包持仓。",
  "See every Fortune token in a wallet.": "查看钱包里的每一个 Fortune 代币。",
  "Balances are read straight from BNB Chain for every Fortune launch, then valued at live curve or pool prices. Nothing is stored, and any address can be looked up.": "余额直接从 BNB Chain 读取，覆盖每一次 Fortune 发行，并按实时曲线或池价格估值。不存储任何数据，任何地址都可以查询。",
  "Launches by this address →": "该地址的发行 →",
  "Show my wallet": "显示我的钱包",
  "BscScan ↗": "BscScan ↗",
  "Connect a wallet": "连接钱包",
  "Fortune only reads your address. Connecting never asks for a signature or spends anything.": "Fortune 只读取你的地址。连接不会请求签名，也不会花费任何资产。",
  "No browser wallet found. Paste an address instead.": "未找到浏览器钱包。请改为粘贴地址。",
  "The wallet did not connect.": "钱包未连接。",
  "Or look up any address": "或查询任意地址",
  "Wallet address": "钱包地址",
  "Enter a 0x address with 40 hex characters.": "请输入以 0x 开头、包含 40 个十六进制字符的地址。",
  "View holdings": "查看持仓",
  "Look up another address": "查询其他地址",
  "View": "查看",
  "Fortune tokens this address holds and the launches it created, read from BNB Chain. An address is public onchain data, not a verified identity.": "该地址持有的 Fortune 代币及其创建的发行，均读取自 BNB Chain。地址是公开的链上数据，并非经过验证的身份。",
  "LAUNCHES": "发行",
  "Launched by this address": "该地址创建的发行",
  "No launches from this address": "该地址没有发行",
  "ONCHAIN READ UNAVAILABLE": "链上读取不可用",
  "This creator's launches could not be verified right now.": "暂时无法验证该创建者的发行。",
  "Launches": "发行",
  "Graduated": "已毕业",
  "On the curve": "曲线中",
  "Graduation rate": "毕业率",
  "The Fortune factory has no launches recorded for this address.": "Fortune 工厂没有记录该地址的发行。",
  "Creator holds": "创建者持有",
  "Newest launches": "最新发行",
  "Older launches →": "更早的发行 →",
  "Counts cover every launch this address created. “Creator holds” is the creator wallet's balance now; tokens moved to other wallets are not attributed to the creator.": "统计涵盖该地址创建的每一次发行。“创建者持有”是创建者钱包当前的余额；转移到其他钱包的代币不计入创建者。",
  "Rescued": "已救援",
  "First Fortune launch": "首次 Fortune 发行",
  "Creator history →": "创建者历史 →",
  "Portfolio": "投资组合",
  "Skip to content": "跳到主要内容",
  "· Tracks": "· 追踪",
  "TOKENIZED STOCK": "代币化股票",
  "TOKENIZED ETF": "代币化 ETF",
  "GOLD & COMMODITIES": "黄金与大宗商品",
  "PRE-IPO TOKEN": "IPO 前代币",
  "CRYPTO": "加密资产",
  "Tracks": "追踪",
  "Launch paired with": "发行并配对",
  "24h change unavailable": "24 小时涨跌暂无数据",
  "Onchain supply × price": "链上供应量 × 价格",
  "All tracked venues": "所有追踪的交易场所",
  "Data source": "数据来源",
  "Refreshed every few minutes": "每隔几分钟刷新",
  "Live data unavailable right now": "实时数据暂不可用",
  "Tokenized stocks trade onchain 24/7. Outside US market hours the price can drift from the listed share and gap at the next open.": "代币化股票在链上 24/7 交易。美股交易时段以外，价格可能偏离上市股票，并在下次开盘时跳空。",
  "FORTUNE PAIRING": "FORTUNE 配对",
  "Eligibility could not be checked right now": "暂时无法检查资格",
  "Fortune reads its onchain Asset Registry for every check. Try again in a minute.": "Fortune 每次检查都会读取链上资产注册表。请稍后再试。",
  "Launches can pair with": "发行可以配对",
  "Discovery is broad; reserve custody is strict. Only registry-approved, oracle-healthy assets can hold launch reserves.": "发现范围广泛，储备托管严格。只有经注册表批准且预言机健康的资产才能持有发行储备。",
  "Launch with an approved pair →": "使用已批准的配对资产发行 →",
  "CONTRACT": "合约",
  "On BNB Smart Chain": "在 BNB Smart Chain 上",
  "Issuer": "发行方",
  "Upgradeable: the issuer can replace the contract's code behind a proxy.": "可升级：发行方可以通过代理合约替换合约代码。",
  "Not upgradeable: the contract's code is fixed.": "不可升级：合约代码是固定的。",
  "Pausable: the issuer can stop all transfers.": "可暂停：发行方可以停止所有转账。",
  "No pause switch found.": "未发现暂停开关。",
  "Rebasing: balances follow a share multiplier, for example after splits or dividends.": "变基：余额随份额乘数变化，例如拆股或分红之后。",
  "Fixed balances: no share multiplier.": "余额固定：没有份额乘数。",
  "Address and controls verified onchain at block": "地址和控制项已在链上验证，区块",
  "Address and controls come from Fortune's verified pair-universe snapshot.": "地址和控制项来自 Fortune 已验证的配对资产快照。",
  "SAME STOCK, OTHER ISSUERS": "同一股票，其他发行方",
  "on BNB Chain": "在 BNB Chain 上",
  "Each issuer's token is a separate contract with its own controls, liquidity and eligibility.": "每个发行方的代币都是独立合约，拥有各自的控制项、流动性和资格。",
  "Controls": "控制项",
  "Upgradeable": "可升级",
  "Pausable": "可暂停",
  "Rebasing": "变基",
  "None found": "未发现",
  "Fortune lists assets that exist on BNB Chain so launches can be compared honestly. A listing is not an endorsement, and tokenized stocks are issuer claims with their own terms and eligibility rules.": "Fortune 列出 BNB Chain 上真实存在的资产，以便如实比较。列出不代表背书，代币化股票是发行方的权益凭证，有各自的条款和资格规则。",
  "Full asset page →": "完整资产页面 →",
  "Breadcrumb": "页面路径",
  "/ 4096 UTF-8 bytes": "/ 4096 UTF-8 字节",
  "https://… or ipfs://…": "https://… 或 ipfs://…",
  "https://…/metadata.json or ipfs://…": "https://…/metadata.json 或 ipfs://…",
  "· Curve": "· 曲线",
  "% of target": "%（占毕业目标）",
  "WALLET · CHAIN": "钱包 · 链",
  "ONCHAIN TOKEN · CHAIN": "链上代币 · 链",
  "Accounted reserve": "已记账储备",
  "ONCHAIN IDENTIFIERS": "链上标识",
  "Trade on market →": "前往市场交易 →",
  "Creator record": "创建者记录",
  "Paired with:": "配对资产：",
  "Token launch details": "代币发行详情",
  "Launch draft": "发行草稿",
  "Live BSC Testnet service readiness": "BSC 测试网服务实时就绪状态",
  "Full protocol + Pancake infrastructure readiness": "完整协议与 Pancake 基础设施就绪状态",
  "Published public-alpha protocol configuration": "已发布的公开测试版协议配置",
  "Measured release-validation results": "发布验证的实测结果",
  "Validate a launch configuration": "验证发行配置",
  "Resolve transaction status before retrying": "重试前确认交易状态",
  "Launches recorded by the Fortune factories, newest first": "Fortune 工厂记录的发行，最新的在前",
  "Prices, market caps and trade activity; ?tokens= for a watchlist": "价格、市值和交易活动；使用 ?tokens= 查询关注列表",
  "One market: chart, pair reserves, supply split and recent trades": "单个市场：图表、配对储备、供应量分布和最近交易",
  "Every Fortune token a wallet holds, valued at live prices": "钱包持有的每一个 Fortune 代币，按实时价格估值",
  "A creator's launches, graduation record and current holdings": "创建者的发行、毕业记录和当前持仓",
  "BNB Chain stocks, RWA, pre-IPO and crypto pair assets with eligibility": "BNB Chain 上的股票、RWA、IPO 前和加密配对资产及其资格",
  "Simulating transfers of this token…": "正在模拟该代币的转账…",
  "PAIR TOKEN CHECK": "配对代币检查",
  "decimals": "位小数",
  "Buying": "买入",
  "Selling": "卖出",
  "wallet → curve": "钱包 → 曲线",
  "curve → wallet": "曲线 → 钱包",
  "curve → pool": "曲线 → 资金池",
  "Fails": "失败",
  "Works as a custom pair": "可作为自定义配对",
  "No transfer tax measured and no issuer controls found in its bytecode.": "未测得转账税，字节码中也未发现发行方控制功能。",
  "Works, with warnings": "可用，但有警告",
  "The curve handles this token, but read every warning before launching.": "曲线可以处理该代币，但发行前请阅读每一条警告。",
  "Not supported": "不支持",
  "A custom-pair curve could not trade this token safely.": "自定义配对曲线无法安全地交易该代币。",
  "Not a token contract": "不是代币合约",
  "There is no contract code at this address on this network.": "该网络上此地址没有合约代码。",
  "Not a readable BEP-20": "无法读取的 BEP-20",
  "decimals() or totalSupply() did not answer, so a curve cannot price it.": "decimals() 或 totalSupply() 没有响应，曲线无法为其定价。",
  "Too many decimals": "小数位过多",
  "Custom pairs support up to 36 decimals.": "自定义配对最多支持 36 位小数。",
  "Transfers fail": "转账失败",
  "At least one transfer the curve needs reverted: the token may be paused, restricted to approved wallets, or block contracts.": "曲线所需的至少一笔转账被回滚：该代币可能已暂停、仅限获批钱包，或禁止合约地址。",
  "Nothing arrives": "到账为零",
  "A transfer went through but the recipient received nothing (a 100% tax).": "转账成功，但接收方什么也没收到（100% 的税）。",
  "Tax charged on top": "额外加收的税",
  "The sender loses more than it sends. The curve can only absorb this from fees, so sells stop once fees run out.": "发送方损失的比发送的更多。曲线只能用手续费吸收这部分，手续费用完后卖出就会停止。",
  "Tax when buying": "买入时的税",
  "Part of what a buyer sends never reaches the curve. Only what arrives buys tokens.": "买家发送的一部分到不了曲线。只有实际到账的部分用于购买代币。",
  "Tax when selling": "卖出时的税",
  "Sellers receive less than the curve pays out. Slippage limits use what actually arrives.": "卖家收到的少于曲线支付的金额。滑点限制按实际到账金额计算。",
  "Tax at graduation": "毕业时的税",
  "The pool receives less than the curve sends. The pool is seeded at the curve price for what arrived.": "资金池收到的少于曲线发送的金额。资金池按曲线价格、以实际到账的数量注入。",
  "Very high tax": "税率极高",
  "More than 25% disappears on a transfer. Every trade loses that much in both directions.": "每次转账会损失超过 25%。每笔交易在买卖两个方向都会损失这么多。",
  "Its code can be replaced by an admin, so any behaviour here can change later.": "管理员可以替换其代码，因此这里的任何行为以后都可能改变。",
  "Can be paused": "可被暂停",
  "An admin can stop transfers. Trading and graduation stop too; rescue opens after seven days.": "管理员可以停止转账。交易和毕业也会随之停止；七天后可开启救援。",
  "Blacklist functions": "黑名单功能",
  "An admin can block addresses, including a curve or its pool.": "管理员可以封禁地址，包括曲线或其资金池。",
  "Tax can change": "税率可被修改",
  "An admin function can change the transfer tax after you launch.": "发行后，管理员函数可以修改转账税。",
  "Transaction or wallet limits": "交易或钱包限额",
  "Max-transaction or max-wallet rules can block large buys or the pool at graduation.": "单笔交易上限或钱包持有上限可能阻止大额买入，或在毕业时阻止资金池。",
  "Rebasing balances": "变基余额",
  "Balances can grow or shrink on their own. Growth becomes pool liquidity; shrinkage hits fees first.": "余额会自行增减。增加的部分成为资金池流动性；减少的部分先由手续费承担。",
  "Mintable": "可增发",
  "New supply can be minted by an authorised account.": "获授权的账户可以增发新代币。",
  "Has an owner": "设有所有者",
  "An owner address is set. Check what it can do on BscScan.": "已设置所有者地址。请在 BscScan 上查看它能做什么。",
  "Transfers not simulated": "未模拟转账",
  "No balance could be found to simulate with. Connect a wallet that holds this token and check again. Launch stays blocked until the simulation succeeds.": "找不到可用于模拟的余额。请连接持有该代币的钱包后重新检查。模拟成功前，发行将保持阻止状态。",
  "Simulated from a DEX pool": "从 DEX 资金池模拟",
  "The only balance found was in a DEX pool, where some tokens apply their own trading tax.": "唯一找到的余额在 DEX 资金池中，部分代币会在那里收取自己的交易税。",
  "Simulation unavailable": "模拟不可用",
  "The network did not answer the transfer simulation. Launch stays blocked; try again in a minute.": "网络没有响应转账模拟。发行将保持阻止状态；请一分钟后重试。",
  "Transfers simulated from a fresh wallet": "转账模拟自一个全新钱包，",
  "Transfers simulated from your wallet": "转账模拟自你的钱包，",
  "Transfers simulated from the burn address": "转账模拟自销毁地址，",
  "Transfers simulated from the owner address": "转账模拟自所有者地址，",
  "Transfers simulated from an exchange wallet": "转账模拟自交易所钱包，",
  "Transfers simulated from a DEX pool": "转账模拟自 DEX 资金池，",
  "Checked": "检查于",
  "at block": "区块",
  "A simulation, not an audit: issuers can change taxes, pause or blacklist later.": "这是模拟，不是审计：发行方以后可能修改税率、暂停转账或拉黑地址。",
  "The token could not be checked right now.": "暂时无法检查该代币。",
  "CUSTOM PAIRS · BETA": "自定义配对 · 测试版",
  "Pair with any token.": "与任意代币配对。",
  "Paste any BEP-20, including tokenized stocks and tokens with a transfer tax. Fortune measures how it behaves, then your launch trades against it on its own curve.": "粘贴任意 BEP-20，包括代币化股票和带转账税的代币。Fortune 会先测量它的行为，然后你的发行在独立曲线上与它交易。",
  "UNAUDITED BETA · BNB SMART CHAIN TESTNET": "未审计测试版 · BNB SMART CHAIN 测试网",
  "UNAUDITED BETA · BNB SMART CHAIN": "未审计测试版 · BNB SMART CHAIN",
  "NOT DEPLOYED ON THIS NETWORK YET": "尚未在此网络部署",
  "Custom-pair contracts are separate from the frozen Standard candidate and have not been audited. Fortune does not review pair tokens; the check below measures them but is not an audit.": "自定义配对合约独立于已冻结的 Standard 候选版本，本身尚未审计。Fortune 不审核配对代币；下方检查会测量它们，但不是审计。",
  "Custom pairs stay off BNB Smart Chain mainnet until their own audit passes. You can still check any token below.": "自定义配对在通过独立审计前不会在 BNB Smart Chain 主网开放。你仍可在下方检查任意代币。",
  "The custom-pairs beta factory has not been deployed on this network yet. You can already check any token below.": "自定义配对测试版工厂尚未在此网络部署。你已经可以在下方检查任意代币。",
  "Custom-pair launch details": "自定义配对发行详情",
  "Pair token": "配对代币",
  "Pair token address": "配对代币地址",
  "Testnet tokens with a faucet:": "带水龙头的测试网代币：",
  "tSTONK · 5% transfer tax": "tSTONK · 5% 转账税",
  "tSHARE · no tax": "tSHARE · 无税",
  "Fortune simulates a buy, a sell and a graduation transfer of the token and measures what actually arrives. Taxes are allowed; tokens that revert or charge tax on top are not.": "Fortune 会模拟该代币的一次买入、一次卖出和一次毕业转账，并测量实际到账的数量。允许转账税；会回滚或额外加收税的代币不被支持。",
  "Stored onchain with your launch. It cannot be edited later.": "随发行一起存储在链上，之后无法修改。",
  "/ 1024 UTF-8 bytes": "/ 1024 UTF-8 字节",
  "Curve and fees": "曲线与费用",
  "Creator fee on every curve trade": "每笔曲线交易的创作者费",
  "Made in the launch transaction. The Launch Shield applies to it too.": "在发行交易中完成。发行护盾同样适用。",
  "The Launch Shield takes up to 99% of every buy in the first five seconds, including this one. It never goes to the creator: it stays in the curve and becomes pool liquidity at graduation.": "发行护盾会在开盘前五秒内收取每笔买入最高 99%，这笔也不例外。它绝不归创建者：会留在曲线中，并在毕业时成为资金池流动性。",
  "Choose a pair token": "选择配对代币",
  "Checking the pair token…": "正在检查配对代币…",
  "This pair token is not supported.": "该配对代币不受支持。",
  "Pair token checked": "配对代币已检查",
  "Identity complete": "身份信息已完成",
  "Curve and first buy set": "曲线和首购已设置",
  "Add a name (up to 64 bytes).": "请填写名称（最多 64 字节）。",
  "Add a ticker (up to 16 bytes).": "请填写代码（最多 16 字节）。",
  "Add an image.": "请添加图片。",
  "Keep the description under 1,024 bytes.": "描述请控制在 1,024 字节以内。",
  "Each link must be at most 256 bytes.": "每个链接最多 256 字节。",
  "Enter a supply and a graduation target.": "请输入供应量和毕业目标。",
  "Supply must be between 1 million and 1 trillion tokens.": "供应量必须在 100 万到 1 万亿枚之间。",
  "The graduation target is outside the supported range.": "毕业目标超出支持范围。",
  "Enter the first buy as a number.": "请以数字输入首购金额。",
  "This first buy would exceed the 2% early-wallet cap and revert. Lower it.": "这笔首购会超过早期钱包 2% 的上限并被回滚。请降低金额。",
  "Launch custom pair on BSC Testnet →": "在 BSC 测试网发行自定义配对 →",
  "Launch custom pair on BNB Chain →": "在 BNB Chain 发行自定义配对 →",
  "Custom pairs are not live on this network": "自定义配对尚未在此网络上线",
  "Working…": "处理中…",
  "Connecting your wallet…": "正在连接钱包…",
  "Running the factory preflight…": "正在运行工厂预检…",
  "Simulating the launch and first buy…": "正在模拟发行和首购…",
  "Simulating the launch…": "正在模拟发行…",
  "Confirm the launch in your wallet…": "请在钱包中确认发行…",
  "Waiting for BNB Chain to confirm…": "等待 BNB Chain 确认…",
  "Launched. Your curve is live.": "发行成功，你的曲线已上线。",
  "Open your market →": "打开你的市场 →",
  "HOW IT WORKS": "运作方式",
  "How custom pairs work": "自定义配对如何运作",
  "Transfer taxes": "转账税",
  "Measured, never counted as reserve": "实测，绝不计入储备",
  "In pair-token units": "以配对代币计价",
  "99% → 0 in 5s · 2% cap for 15s": "5 秒内 99% → 0 · 15 秒内 2% 上限",
  "Pancake V2 · LP burned": "Pancake V2 · LP 已销毁",
  "If the pair breaks": "若配对代币出问题",
  "Pro-rata rescue": "按比例救援",
  "Want a registry-approved pair instead?": "想要注册表批准的配对？",
  "Standard launch →": "Standard 发行 →",
  "How custom pairs work →": "了解自定义配对 →",
  "New custom-pair launches are paused right now.": "新的自定义配对发行目前已暂停。",
  "The name must be 1 to 64 bytes.": "名称必须为 1 到 64 字节。",
  "The ticker must be 1 to 16 bytes.": "代码必须为 1 到 16 字节。",
  "The description must be at most 1,024 bytes.": "描述最多 1,024 字节。",
  "The creator fee can be at most 1%.": "创作者费最多 1%。",
  "The pair token has no contract code on this network.": "该配对代币在此网络上没有合约代码。",
  "That address is a Fortune curve, not a token.": "该地址是 Fortune 曲线，不是代币。",
  "The pair token's decimals could not be read or are above 36.": "无法读取配对代币的小数位，或其超过 36。",
  "The pair token does not answer basic BEP-20 reads.": "该配对代币不响应基本的 BEP-20 读取。",
  "The launch did not go through.": "发行未完成。",
  "The launch transaction reverted.": "发行交易被回滚。",
  "The transaction confirmed but no launch event was found.": "交易已确认，但未找到发行事件。",
  "You rejected the request in your wallet.": "你在钱包中拒绝了请求。",
  "The transaction did not go through.": "交易未完成。",
  "CUSTOM PAIR · BETA": "自定义配对 · 测试版",
  "Custom pairs": "自定义配对",
  "Paired with": "配对",
  "Rescue": "救援",
  "LP burned forever": "LP 永久销毁",
  "Pool depth": "资金池深度",
  "Trades": "交易笔数",
  "TRADE ON THE CURVE": "在曲线上交易",
  "READY TO GRADUATE": "即将毕业",
  "GRADUATED · PANCAKE V2": "已毕业 · PANCAKE V2",
  "RESCUE OPEN": "救援已开启",
  "ON THE CURVE": "曲线交易中",
  "Trading moved to PancakeSwap": "交易已转至 PancakeSwap",
  "Redeem for your share": "赎回你的份额",
  "The curve is complete": "曲线已完成",
  "Trade side": "交易方向",
  "Slippage tolerance": "滑点容忍度",
  "Slippage": "滑点",
  "Max": "最大",
  "Over the 2% early-wallet cap for the first 15 seconds. Lower the amount or wait.": "超过前 15 秒每个钱包 2% 的上限。请降低金额或稍后再试。",
  "The target is reached and trading is closed. Anyone can move the reserve into a new PancakeSwap V2 pool at the final curve price; the LP tokens are burned.": "已达到目标，交易已关闭。任何人都可以按曲线最终价格把储备转入新的 PancakeSwap V2 资金池；LP 代币会被销毁。",
  "Graduate to PancakeSwap →": "毕业至 PancakeSwap →",
  "Trade on PancakeSwap ↗": "在 PancakeSwap 交易 ↗",
  "Pool ↗": "资金池 ↗",
  "Open rescue": "开启救援",
  "Claim creator fees": "领取创作者手续费",
  "CONTRACTS": "合约",
  "Pancake V2 pool": "Pancake V2 资金池",
  "Launch Shield reserve": "发行护盾储备",
  "Custom-pair contracts are an unaudited beta, separate from Fortune's frozen Standard candidate.": "自定义配对合约是未审计的测试版，独立于 Fortune 已冻结的 Standard 候选版本。",
  "Preparing your buy…": "正在准备买入…",
  "Preparing your sell…": "正在准备卖出…",
  "Simulating the buy…": "正在模拟买入…",
  "Confirm the buy in your wallet…": "请在钱包中确认买入…",
  "Simulating the sell…": "正在模拟卖出…",
  "Confirm the sell in your wallet…": "请在钱包中确认卖出…",
  "Bought.": "买入成功。",
  "Bought. This buy completed the curve: anyone can now graduate it.": "买入成功。这笔买入完成了曲线：现在任何人都可以让它毕业。",
  "Sold.": "卖出成功。",
  "The buy reverted.": "买入被回滚。",
  "The sell reverted.": "卖出被回滚。",
  "Preparing graduation…": "正在准备毕业…",
  "Graduated. Trading continues on PancakeSwap.": "已毕业，交易在 PancakeSwap 继续。",
  "Opening rescue…": "正在开启救援…",
  "Rescue is open.": "救援已开启。",
  "Claiming creator fees…": "正在领取创作者手续费…",
  "Creator fees claimed.": "创作者手续费已领取。",
  "Preparing your redemption…": "正在准备赎回…",
  "Redeemed.": "赎回成功。",
  "The redemption reverted.": "赎回被回滚。",
  "The transaction reverted.": "交易被回滚。",
  "Reading the curve from BNB Chain…": "正在从 BNB Chain 读取曲线…",
  "This launch could not be read right now.": "暂时无法读取该发行。",
  "BNB Chain did not answer. Nothing is wrong with your funds; try again in a minute.": "BNB Chain 没有响应。你的资金没有问题；请一分钟后重试。",
  "Custom pairs let anyone launch against any BEP-20. Fortune does not review or endorse pair tokens, and these contracts have not been audited.": "自定义配对让任何人都能与任意 BEP-20 配对发行。Fortune 不审核也不背书配对代币，这些合约也尚未审计。",
  "CUSTOM PAIRS · BETA · UNAUDITED": "自定义配对 · 测试版 · 未审计",
  "Paired with any token": "与任意代币配对",
  "Pair with any token": "与任意代币配对",
  "Launch a custom pair →": "发行自定义配对 →",
  "Check a token →": "检查代币 →",
  "Launch against any BEP-20, including tokenized stocks and tokens with a transfer tax. Check how a token behaves before you launch.": "与任意 BEP-20 配对发行，包括代币化股票和带转账税的代币。发行前先检查代币的行为。",
  "Custom-pair launches could not be read right now.": "暂时无法读取自定义配对发行。",
  "No custom-pair launches yet.": "还没有自定义配对发行。",
  "The first one will appear here, read straight from the custom-pair factory.": "第一个发行会直接从自定义配对工厂读取并显示在这里。",
  "Custom pair · beta": "自定义配对 · 测试版",
  "Any BEP-20, including transfer-tax tokens · unaudited": "任意 BEP-20，包括带转账税的代币 · 未审计",
  "Want a token that is not approved here, such as any tokenized stock or a transfer-tax token?": "想用这里未获批的代币，比如任意代币化股票或带转账税的代币？",
  "Try custom pairs (beta) →": "试试自定义配对（测试版）→",
  "Custom pairs (beta)": "自定义配对（测试版）",
  "Pair with any token, including ones that tax transfers.": "与任意代币配对，包括收取转账税的代币。",
  "Custom pairs are the permissionless path: paste any BEP-20, such as a tokenized stock that is not in the registry or a token with a transfer tax, and launch against it. There is no registry and no oracle. Each launch gets its own curve priced in the pair token, so a badly behaved pair can only affect launches that chose it.": "自定义配对是无需许可的路径：粘贴任意 BEP-20，比如不在注册表中的代币化股票或带转账税的代币，即可与之配对发行。没有注册表，也没有预言机。每个发行都有自己以配对代币计价的曲线，因此行为不良的配对代币只会影响选择了它的发行。",
  "Transfer taxes are measured, not trusted.": "转账税靠实测，而不是信任。",
  "The curve counts only what actually arrives, checks sell slippage against what reaches the seller, and seeds the pool from what the pool received.": "曲线只计算实际到账的数量，按卖家实际收到的金额检查卖出滑点，并按资金池实际收到的数量注入资金池。",
  "Check a token before you launch.": "发行前先检查代币。",
  "Fortune simulates a buy, a sell and a graduation transfer and reports the tax on each, plus pause, blacklist, fee-change, limit and rebasing functions found in the bytecode.": "Fortune 会模拟一次买入、一次卖出和一次毕业转账，报告每一步的税，以及字节码中发现的暂停、黑名单、改税、限额和变基功能。",
  "Same Launch Shield.": "同样的发行护盾。",
  "99% decaying to zero within five seconds and a 2% wallet cap for fifteen seconds. Shield tax becomes pool liquidity and is never paid to the creator.": "99% 在五秒内衰减为零，前十五秒每个钱包上限 2%。护盾税会成为资金池流动性，绝不支付给创建者。",
  "Graduation to PancakeSwap V2.": "毕业至 PancakeSwap V2。",
  "The pool is created in the launch transaction and locked until graduation, then opened at the final curve price with the LP tokens burned.": "资金池在发行交易中创建并锁定至毕业，然后以曲线最终价格开放，LP 代币被销毁。",
  "If the pair token breaks.": "如果配对代币出问题。",
  "Losses hit Launch Shield reserve and unclaimed fees first. If the reserve itself falls short, or graduation stays impossible for seven days, holders redeem a pro-rata share of everything the curve holds.": "损失先由发行护盾储备和未领取的手续费承担。如果储备本身不足，或毕业连续七天无法完成，持有者可按比例赎回曲线持有的全部资产。",
  "Unaudited beta, separate from the frozen Standard candidate. The site never enables it on BNB Smart Chain mainnet until it passes its own audit.": "未审计测试版，独立于已冻结的 Standard 候选版本。在通过独立审计之前，本站绝不会在 BNB Smart Chain 主网启用它。",
  "Check a token or launch →": "检查代币或发行 →",
  "The permissionless alternative is the": "无需许可的替代方案是",
  "custom-pairs beta": "自定义配对测试版",
  "· Paired with": "· 配对",
  "Fees": "手续费",
  "Prices are shown in the pair token. Its issuer can change its taxes, pause it or blacklist addresses.": "价格以配对代币显示。其发行方可以修改税率、暂停转账或拉黑地址。",
  "Fortune could not read markets from BNB Chain.": "Fortune 无法从 BNB Chain 读取市场。",
  "DOCS · BNB SMART CHAIN": "文档 · BNB SMART CHAIN",
  "Fortune is built around three rules: no reward-funded token dumping, holders get paid in the pair asset, and creators can pair launches with an expanding universe of reviewed BNB assets. The interface stays simple while the registry, oracle and graduation checks stay explicit underneath.": "Fortune 围绕三条规则构建：不用奖励资金砸盘，持有者以配对资产获得收益，创建者可以把发行与不断扩展的已审核 BNB 资产配对。界面保持简单，注册表、预言机和毕业检查则在底层清晰可查。",
  "Launch →": "发行 →",
  "How a Fortune launch works": "Fortune 发行如何运作",
  "Burn + Rewards": "销毁 + 奖励",
  "Locked Pancake liquidity": "锁定的 Pancake 流动性",
  "Holder rewards": "持有者奖励",
  "Pair assets on BNB": "BNB 上的配对资产",
  "Any reviewed BEP-20": "任意已审核的 BEP-20",
  "Launching a token": "发行代币",
  "What you have to trust": "你需要信任什么",
  "API and addresses": "API 与地址",
  "HOW": "运作方式",
  "A creator chooses a token identity, launch type and pair asset. Fortune validates that configuration against the live registry and oracle policy, deploys a fixed-supply token and opens its curve. When the launch reaches its graduation condition, the standard stack can migrate into Pancake V3 and permanently custody the LP-position NFT in Fortune's locker.": "创建者选择代币身份、发行类型和配对资产。Fortune 根据实时注册表和预言机策略验证该配置，部署固定供应量的代币并开启其曲线。当发行达到毕业条件时，标准架构可迁移至 Pancake V3，并把 LP 头寸 NFT 永久托管在 Fortune 的锁仓合约中。",
  "BURN + REWARDS": "销毁 + 奖励",
  "A separate, stricter launch architecture": "一套独立且更严格的发行架构",
  "Fortune's production target is Burn + Rewards v2: token-side market fees can only enter an irreversible burn path, while pair-asset fees fund rewards and platform routing directly. Fortune should never need to sell the launch token to pay holders. The older fee-on-transfer stack remains research/testnet evidence and is not being silently shipped as v2.": "Fortune 的生产目标是销毁 + 奖励 v2：代币侧的市场手续费只能进入不可逆的销毁路径，而配对资产手续费直接用于奖励和平台分配。Fortune 永远不需要卖出发行代币来支付持有者。较早的转账税架构仍只是研究/测试网证据，不会被悄悄当作 v2 上线。",
  "Burn + Rewards v2 status:": "销毁 + 奖励 v2 状态：",
  "research only, disabled for real funds": "仅限研究，真实资金禁用",
  "GRADUATION": "毕业",
  "Standard graduation uses Fortune's Pancake V3 adapter. The curve preflights the market, transfers the graduation inventory atomically, mints the LP position and deposits the NFT into the permanent Fortune liquidity locker. Failed graduation remains retryable rather than partially completing.": "Standard 毕业使用 Fortune 的 Pancake V3 适配器。曲线先预检市场，原子化转移毕业库存，铸造 LP 头寸，并把 NFT 存入永久的 Fortune 流动性锁仓合约。失败的毕业可以重试，而不会只完成一部分。",
  "REWARDS": "奖励",
  "Public accounting before flashy APY.": "先公开记账，再谈亮眼的 APY。",
  "Fortune will expose reward pots, epochs and distribution transactions only when they can be reproduced from chain data. The extended stack already separates holder-dividend accounting from the normal Standard token path; production automation remains a separate review boundary.": "只有当奖励池、周期和分发交易能从链上数据复现时，Fortune 才会公开它们。扩展架构已把持有者分红记账与普通 Standard 代币路径分开；生产自动化仍是单独的审核边界。",
  "THE BNB ADVANTAGE": "BNB 优势",
  "Pair assets go far beyond one native coin.": "配对资产远不止一种原生币。",
  "Fortune's registry model can represent BNB/majors, stablecoins, BNB-native DeFi assets and compatible tokenized stocks/RWAs. A discovered BSC token is not automatically launchable: an exact contract, compatible transfer behavior, oracle policy and graduation path must all pass.": "Fortune 的注册表模型可以涵盖 BNB/主流币、稳定币、BNB 原生 DeFi 资产以及兼容的代币化股票/RWA。被发现的 BSC 代币并不会自动可发行：准确的合约、兼容的转账行为、预言机策略和毕业路径都必须通过。",
  "ANY REVIEWED BEP-20": "任意已审核的 BEP-20",
  "“Paste a contract” is the destination, not an excuse to skip checks.": "“粘贴合约”是目标，而不是跳过检查的借口。",
  "Fortune can expand toward arbitrary BEP-20 pairs, but BNB tokens can have fees, rebases, blacklists, unusual decimals or thin liquidity. Fortune therefore treats custom pairing as a compatibility pipeline: token behavior, pricing source, liquidity/graduation venue and policy checks must pass before the asset becomes launchable. The permissionless alternative is the": "Fortune 可以扩展到任意 BEP-20 配对，但 BNB 上的代币可能有手续费、变基、黑名单、特殊小数位或流动性不足。因此 Fortune 把自定义配对视为兼容性流程：代币行为、定价来源、流动性/毕业场所和策略检查都必须通过，资产才可发行。无需许可的替代方案是",
  "LAUNCH": "发行",
  "Simple by default, advanced when needed.": "默认简单，需要时再进阶。",
  "The product direction is a short default flow: identity, image, launch type, pair asset and optional creator purchase. Fortune's deeper curve, fee and routing controls remain available for reviewed advanced launch templates rather than overwhelming every creator.": "产品方向是简短的默认流程：身份、图片、发行类型、配对资产和可选的创建者购买。Fortune 更深入的曲线、手续费和分配控制保留给经过审核的高级发行模板，而不会让每位创建者不知所措。",
  "TRUST MODEL": "信任模型",
  "Less trust, stated plainly.": "更少的信任，直白地说明。",
  "You still trust BNB Smart Chain consensus and the external protocols a launch uses, including WBNB, approved oracle feeds and PancakeSwap. Fortune's own production release additionally depends on independent contract review, contract-based governance, monitored RPC infrastructure and a paused-then-activated deployment ceremony.": "你仍需信任 BNB Smart Chain 共识以及发行所用的外部协议，包括 WBNB、获批的预言机喂价和 PancakeSwap。Fortune 自身的生产发布还依赖独立的合约审查、基于合约的治理、受监控的 RPC 基础设施，以及先暂停后激活的部署流程。",
  "API + ADDRESSES": "API + 地址",
  "Use the same data Fortune uses.": "使用 Fortune 同样的数据。",
  "Public endpoints cover protocol metadata, assets, pairs, tokenized-stock discovery, launches, readiness, transactions, stats and revenue state. Production contract addresses remain visible through Fortune status pages and BscScan.": "公开接口涵盖协议元数据、资产、配对、代币化股票发现、发行、就绪状态、交易、统计和收入状态。生产合约地址可通过 Fortune 状态页面和 BscScan 查看。",
};

// Code containers are skipped entirely. A textarea's typed text is never
// translated, but its placeholder and label attributes still are.
const UNTRANSLATED_TAGS = new Set(["SCRIPT", "STYLE", "NOSCRIPT", "TEMPLATE"]);
const UNTRANSLATED_SELECTOR = '[translate="no"], script, style, noscript, template, textarea';

function translateText(input: string) {
  const leading = input.match(/^\s*/)?.[0] || "";
  const trailing = input.match(/\s*$/)?.[0] || "";
  const normalized = input.trim().replace(/\s+/g, " ");

  if (!normalized) return input;

  const exact = ZH[normalized];
  if (exact) return leading + exact + trailing;

  let output = normalized;
  const replacements = Object.entries(ZH)
    .filter(([key]) => key.length >= 12 && output.includes(key))
    .sort((a, b) => b[0].length - a[0].length);

  for (const [english, chinese] of replacements) {
    output = output.replaceAll(english, chinese);
  }

  return leading + output + trailing;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const originals = useRef(new WeakMap<Text, string>());
  const attributeOriginals = useRef(
    new WeakMap<Element, Map<string, string>>()
  );
  const applying = useRef(false);

  const setLanguage = useCallback((next: Language) => {
    setLanguageState(next);
    try {
      window.localStorage.setItem("fortune-language", next);
    } catch {
      // Storage is optional.
    }
  }, []);

  useEffect(() => {
    try {
      const stored = window.localStorage.getItem("fortune-language");
      if (stored === "zh" || stored === "en") {
        setLanguageState(stored);
      }
    } catch {
      // English remains the default.
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === "zh" ? "zh-CN" : "en";

    const translateNode = (node: Node) => {
      // User-supplied values (token names, URIs) opt out with translate="no".
      // Script, style and template text is code, not copy: Next.js streams the
      // server-component payload in inline scripts, and rewriting one before it
      // runs would change the data React renders.
      if (node instanceof Element && (node.getAttribute("translate") === "no" || UNTRANSLATED_TAGS.has(node.tagName))) {
        return;
      }

      if (node.nodeType === Node.TEXT_NODE) {
        const text = node as Text;
        if (text.parentElement?.closest(UNTRANSLATED_SELECTOR)) return;
        const current = text.nodeValue || "";

        if (!originals.current.has(text)) {
          originals.current.set(text, current);
        }

        const original = originals.current.get(text) || current;
        const next = language === "zh" ? translateText(original) : original;

        if (text.nodeValue !== next) {
          text.nodeValue = next;
        }
        return;
      }

      if (!(node instanceof Element)) return;

      for (const attr of ["placeholder", "title", "aria-label"]) {
        const current = node.getAttribute(attr);
        if (!current) continue;

        let map = attributeOriginals.current.get(node);
        if (!map) {
          map = new Map<string, string>();
          attributeOriginals.current.set(node, map);
        }
        if (!map.has(attr)) map.set(attr, current);

        const original = map.get(attr) || current;
        const next = language === "zh" ? translateText(original) : original;
        if (current !== next) node.setAttribute(attr, next);
      }

      if (node.tagName === "TEXTAREA") return;
      node.childNodes.forEach(translateNode);
    };

    const apply = () => {
      applying.current = true;
      translateNode(document.body);
      applying.current = false;
    };

    apply();

    const observer = new MutationObserver((mutations) => {
      if (applying.current) return;

      applying.current = true;
      for (const mutation of mutations) {
        if (mutation.type === "characterData") {
          const text = mutation.target as Text;
          originals.current.set(text, text.nodeValue || "");
          translateNode(text);
        }

        mutation.addedNodes.forEach((node) => {
          if (node.nodeType === Node.TEXT_NODE) {
            originals.current.set(node as Text, node.nodeValue || "");
          }
          translateNode(node);
        });
      }
      applying.current = false;
    });

    observer.observe(document.body, {
      subtree: true,
      childList: true,
      characterData: true,
    });

    return () => observer.disconnect();
  }, [language]);

  const value = useMemo(
    () => ({ language, setLanguage }),
    [language, setLanguage]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return value;
}
